### PR TITLE
Only read pixel_mask if pixel_mask_applied is False

### PR DESCRIPTION
**Pull request by rjgildea**
Previously the code would only read the `pixel_mask` if `pixel_mask_applied` was both defined and `True`. However, if it is
defined as `True`, then this means the mask has already been applied to the raw data, therefore we don't need to read the mask in order to re-apply the mask. Therefore invert the logic.

Convert function masquerading as a class to a function and add tests.

### CODE REVIEW

**Comment by phyy-nx** [comment]
For both [SwissFEL Jungfrau16M](https://github.com/cctbx/cctbx_project/blob/master/xfel/swissfel/jf16m_cxigeom2nexus.py#L296) and the [EuXFEL AGIPD](https://github.com/cctbx/cctbx_project/blob/master/xfel/euxfel/agipd_cxigeom2nexus.py#L156), I have been setting `pixel_mask_applied=True` if a pixel mask is available.  When I first read your PR I panicked a bit because I thought I had the flag backwards.  Turns out I think I'm only kinda wrong here, because I think both detectors modify the raw data to change the masked pixels to (I think) 0.  That would imply I should be always setting this flag to True, regardless if a mask is available or not, but at least I don't have it the wrong way around.

For reference, [NXmx](https://manual.nexusformat.org/classes/applications/NXmx.html) defines the term:

> True when the pixel mask correction has been applied in the electronics, false otherwise.

We should check the [gold standard datasets](https://journals.iucr.org/m/issues/2020/05/00/ti5018/) (Eiger and Jungfrau16M) to see if the flag is present, what the value is, and verify the affected pixels are set to a number outside the trusted range.

**Comment by phyy-nx** [comment]
Confirmed for the Jungfrau16M.  `pixel_mask_applied=True` and the invalid pixels are set to 0 in the raw data. However, 0 is a valid number because a pedestal is applied and there are negative pixel values.  Therefore the mask still needs to be read and used even though `pixel_mask_applied=True`.

I think instead of inverting the logic of `pixel_mask_applied` in nexus.py, the flag should not be checked at all.  If a mask is supplied in the file, use it, since the spec does not specify what the invalid pixel value would be if the mask has been applied.

**Comment by ndevenish** [comment]
Is this PR still under consideration? It looks like it's a pretty fundamental problem....

**Comment by ndevenish** [comment]
>  If a mask is supplied in the file, use it, since the spec does not specify what the invalid pixel value would be if the mask has been applied.

Does this imply that `pixel_mask_applied` in the standard is functionally useless?

> I think instead of inverting the logic of `pixel_mask_applied` in nexus.py, the flag should not be checked at all. If a mask is supplied in the file, use it, since the spec does not specify what the invalid pixel value would be if the mask has been applied.

This sounds correct given the reasoning above - mask should always be applied if available. @rjgildea ?

**Comment by rjgildea** [comment]
Always applying the mask if available, even if `pixel_mask_applied=True`, will add a not insignificant overhead to per-image analysis (the mask needs to be read from the hdf5 file and converted to a `flex` array, and then applied to the raw image) for no benefit, since the pixel mask has already been applied to the raw data.

**Comment by rjgildea** [comment]
> Confirmed for the Jungfrau16M. `pixel_mask_applied=True` and the invalid pixels are set to 0 in the raw data. However, 0 is a valid number because a pedestal is applied and there are negative pixel values. Therefore the mask still needs to be read and used even though `pixel_mask_applied=True`.
> 
> I think instead of inverting the logic of `pixel_mask_applied` in nexus.py, the flag should not be checked at all. If a mask is supplied in the file, use it, since the spec does not specify what the invalid pixel value would be if the mask has been applied.

Perhaps I'm missing something, but I don't understand what the point is in setting invalid pixels to a valid pixel value in the raw data?

**Comment by phyy-nx** [comment]
> > If a mask is supplied in the file, use it, since the spec does not specify what the invalid pixel value would be if the mask has been applied.
> 
> Does this imply that `pixel_mask_applied` in the standard is functionally useless?
> 

Well, pixel_mask is only recommended in the [spec](https://manual.nexusformat.org/classes/applications/NXmx.html#index-37), so it's possible that pixel_mask_applied=True and pixel_mask=None.  But since it's unknown what the masked pixel value is, I don't know what we'd do with that information.

> Perhaps I'm missing something, but I don't understand what the point is in setting invalid pixels to a valid pixel value in the raw data?

Agree!  I don't know why they do this.  Perhaps it's better to set the pixels to zero then to leave them in a bad state in case downstream software that they don't know about isn't using the provided mask?

**Comment by ndevenish** [comment]
This discrepancy will apparently be dealt with differently now.

**Pull request closed without merging**
