### PR TITLE
New file writer image dimensions

### LINKED ISSUE #657: Loading large experiment lists has become >> 10x slower in recent versions.
I noticed that loading largeish (~1000 experiment SSX) experiment lists has become >10x slower between version 3.14 and the current release (tested on diamond light source modules/filesystem and seeing similar on local machine).
In dials 3.14, a python script that loads this experiment list takes ~4-6s, but on the latest dials takes ~57-73s !

I believe this relates to the change from pkg_resources to importlib:
https://github.com/cctbx/dxtbx/commit/71d4ec04c95739c061d12b551d9cb9f86811134f

I have profiled the two cases, and the time difference is in the _extract_models function, specifically the entry point handling for the profile models and scaling models.

profile

Attached in the zip below are the two cProfiles for running a python script containing
`load.experiment_list("processed_0.ept", check_format=False)`

[profiling.zip](https://github.com/cctbx/dxtbx/files/12407189/profiling.zip)

### PR DESCRIPTION
**Pull request by graeme-winter**
Reported now as slow, fast i.e. correct rather than historical fast, slow which we have always had to invert

Fixes #657

### CODE REVIEW

**Comment by biochem-fan** [comment]
Instead of using the `known_safe` list, how about checking `/entry/instrument/detector/detectorSpecific/eiger_fw_version` is equal or newer than `release-2022.1.2`? Then we can support all detector sizes.

**Comment by graeme-winter** [comment]
> Instead of using the `known_safe` list, how about checking `/entry/instrument/detector/detectorSpecific/eiger_fw_version` is equal or newer than `release-2022.1.2`? Then we can support all detector sizes.

Yes this is a much more sensible idea

**Comment by biochem-fan** [comment]
They privately shared me three datasets:

1. EIGER2 CdTe 4M (FW: release-2022.1.2): broken
2. EIGER 16M (FW: release-2022.1.2): broken
3. EIGER2 16M XE (FW: release-2022.1.1): not broken

This is as explained in https://github.com/cctbx/dxtbx/pull/663#issuecomment-1790353123.

They will upload the dataset 2 to XRDa. I will also ask them to upload the dataset 1 (as an example of a 4M detector).

**Comment by biochem-fan** [comment]
Test data in https://github.com/cctbx/dxtbx/issues/675#issuecomment-1862543417.

**Comment by spmeisburger** [comment]
I think there is a bug in the firmware version check (commit 00acdfc26164a54ee76b20a1ffeeb7fb72c5ae99), should be:

`if version.parse(fw_version_string) < version.parse("2022.1.2"):`

**Comment by biochem-fan** [comment]
@spmeisburger I agree. Great find!

**Comment by biochem-fan** [comment]
@graeme-winter what is blocking merging of this?

**Comment by graeme-winter** [comment]
> @graeme-winter what is blocking merging of this?

Test failures

And the absence of time to review those failures to see if this is some upstream nonsense (which I am certain it is)

I think if you would be kind enough to give the change set a review I will be tempted to abuse my superpowers to squash merge it anyway. This is also annoying me. This may incur the wrath of @ndevenish 🤣

**Comment by biochem-fan** [comment]
@graeme-winter
This looks like `FormatMRC` is causing a test failure.

https://dev.azure.com/azure-dxtbx/dxtbx/_build/results?buildId=5080&view=logs&jobId=9d9185fd-8342-5abc-a33b-b507f89021a3&j=bbfc4e03-b3dc-52f1-d3f9-562e8cca4b84&t=fc34eecf-32f3-5a61-c195-251d92645545

Will rebasing this PR to the latest `main`, which includes https://github.com/cctbx/dxtbx/commit/f903a3c3668e48a9e1c63d5813bfd236bcb179a8, help?

Regarding EIGER itself, it looks fine to me and you have the same test cases as mine.
My only concern is whether all firmware versions start from "release-".
PSI/SLS might run a development version that does not start with "release-".
But this is impossible to tell from outside.

**Comment by graeme-winter** [comment]
Rebased on main

**Pull request merged**
