### PR TITLE
experimentlist refactoring

### PR DESCRIPTION
**Pull request by Anthchirp**
If anyone wants to take a look at this - I had a bit of a rampage through `ExperimentListDict`...
One of the victims was the pretend-class `ExperimentListDumper` which now is mostly gone and the remaining husk throws deprecation warnings.
This is by no means a finished product, but I hope a few steps in the right direction.

dxtbx and dials tests still pass, no dxtbx 3 regressions. There are flake8 warnings, but they are not new.

### CODE REVIEW

**Comment by ndevenish** [comment]
Mostly looks good. My only concern is that the imageset-string-path behaviour now appears to work on all of the models? I'd rather move to eliminating this "feature" rather than allowing it to be expanded.

Along the same lines, I'm not sure there is an actual use case for the splitting functionality any more, other than the tests that use it?

**Comment by phyy-nx** [comment]
I haven't looked at the PR yet but do you mean dials.split_experiments?  I
use that all the time.

Re: ExperimentListDumper, there's only 7 instances of it in xfel so it will
be trivial to replace.

**Comment by Anthchirp** [comment]
Apart from the added deprecation warning and the new methods on `ExperimentList` this should be a pure refactor. If you mean what I think you do then the string-path behaviour is already in place for all models on master.

**Comment by ndevenish** [comment]
> I haven't looked at the PR yet but do you mean dials.split_experiments? I use that all the time.

No, I'm talking about the ability to have experiment_list.json files point to e.g. beam.json, detector.json etc etc for parts of the models. AFAIK it's never been creatable from tooling and am not sure what sort of workflow it might theoretically support.

**Comment by phyy-nx** [comment]
Oh, I didn't remember that we could save a solo detector model to json.
That would be useful for stills metrology.  Right now, I refine 3000
crystal models with one detector model, then use dials.split_expeirments to
get a file with only 1 crystal model + the refined detector, then use that
as my reference geometry.  It's a bit weird to do that since my reference
geometry has an irrelevant crystal model.  A tool called
'dials.split_models' would be useful.  I imagine it would split the models
to separate files.  Then I could have a reference geometry that was only
the detector.

**Comment by ndevenish** [comment]
If you are worried about the extra model it'd probably be better to provide a way to export an experiment with just the geometry information. Splitting into separate files is bad because you might change it, and this magically makes any results in other files that depended on it wrong.

**Pull request merged**
