### PR TITLE
Remove h5rawdata

### LINKED ISSUE #244: Treatment of non-master / non-nxs HDF5 files
Semi-frequent issue with Eiger data: user has

```
ins_1_1_000001.h5
ins_1_1_000002.h5
ins_1_1_000003.h5
ins_1_1_000004.h5
ins_1_1_master.h5
ins_1_1_meta.h5
```

and passes `ins_1_1_000001.h5` to `dials.import` - this obviously cannot work because there is no metadata associated with this file _however_ it appears that we _do_ have a format class which recognises this namely `FormatHDF5RawData.py:FormatRawData` which seems hard coded for:

 - HDF5 containing just `data`
 - `data` being a *one* image data set - if this is not a 1 image data set then world will end because

```
    def get_raw_data(self):
        data = self._h5_handle["data"]
        return flex.int(data[:, :])
```

ohai loading 18 gigapixels via numpy (`p(ends_well) = ε`). 

Questions - 
 - do we need this?
 - can I hack it to impose assertions which are encoded in there?
 - how _should_ we trap user passing incorrect data & help them to get the right thing?

### PR DESCRIPTION
**Pull request by phyy-nx**
Fixes #244.

Depends on #255.  I'll point this one at master when #255 is merged.

### CODE REVIEW

**Comment by ndevenish** [comment]
From discussion in #244, it looks like this format class isn't needed at all now? In which case removal might be better - marking it as deprecated in a comment doesn't really change anything. But a deprecation warning when constructing the class wouldn't stop it being found by the registry.

I guess if one wants to keep it in, it could have a deprecation warning added on construction - and, with #255 in - be marked as abstract by overriding `is_abstract()` - that'd mean it gets ignored by the importer, but could still be manually constructed. This is a bit of a fudge, but less bad than quietly ignoring, and stopping #244 might be worth it.

**Comment by ndevenish** [comment]
I've rebased since this depended on the branch merged in #255

**Comment by phyy-nx** [comment]
Thanks, I'd rather keep it for now, but I could imagine removing it completely in the future.

**Comment by phyy-nx** [comment]
This and dials/dials#1499 should go in at the same time.  @ndevenish ok to merge them both?

**Comment by ndevenish** [comment]
Is it used in any `Registry` scenarios? If it's only going to be called manually we could make `understand() => False`, or we could either do the above (return `is_abstract => True` but not actually mark as abstract).

I'm just not sure what scenarios it's going to be used for if it isn't going to be picked up by a Registry search.

**Comment by ndevenish** [comment]
> This and [dials/dials#1499](https://github.com/dials/dials/pull/1499) should go in at the same time. @ndevenish ok to merge them both?

This actually won't do anything now, as I removed the `ignore()` mechanism. Hence the need to remove it from the Registry mechanism but without removing... whatever usage it still has

**Comment by phyy-nx** [comment]
Oh I see.  Mmmm, removing it entirely is probably easier then.  I'll do it.

**Comment by ndevenish** [comment]
👍 

dials/dials#1499 I'm actually fine going in even without this, as it makes it a failing test for behaviour we want to prevent (though obviously would be xfail if we were putting in for a longer time)

**Pull request merged**
