### PR TITLE
Contiguous NeXus

### PR DESCRIPTION
**Pull request by phyy-nx**
Rewrite of nexus.py to read all panels at once in a multi panel dataset.  Draft PR.

In the recent EuXFEL beam time we were processing data at 2 kHz and we had problems scaling up to many cores so we could keep up with data collection.  After profiling dials.stills_process, we saw that massive amounts of time were spent in dataset_as_flex in nexus.py when using many cores.  This is the function that reads the HDF5 data in C++ directly into flex arrays, bypassing the numpy array.  More specifically, the percentage of time spent in dataset_as_flex increased as the number of MPI cores went up, indicating a problem in scaling up.

We still don't know the source of the scaling problem.  We speculated dataset_as_flex itself might not be optimized, hence this PR, but the changeset here didn't solve the problem on its own.  During the beamtime we solved it by operating on many smaller hdf5 files instead of one big hdf5 file.  This let us keep up with data collection. However, I do think the code here helps.

In nexus.py, for multi-panel data (such as the AGIPD detector which has 256 panels), for each image, a call to dataset_as_flex is made for each panel.  This invokes an HDF5 read for each panel, which may be inefficient as the disc is hit for each panel.  Instead, in this PR I tried reading the data all at once, e.g. all the panels in at the same time in a single HDF5 read, then split the data in memory.

This PR has several problems:

1. It needs more review.  I'm particularly hoping someone can look at the masking code and make sure I didn't break single-panel images :)
2. It relies on the slices comprising data that is contiguous on disc.  There is a [fake assert](https://github.com/cctbx/dxtbx/compare/main...cctbx:contiguous_nexus?expand=1#diff-561673f296e5629bbe2e783ce83757f59f54ffe3bc8151f5767a885f78d58ddeR1323-R1324) in there, but one can imagine code that checks through all the slices, and reverts to old behavior if there are substantial gaps.
3. It's only actually faster if you are using many cores!  Otherwise it's slower!

More on that last point.  Here's an example script to test timing, using the [SwissFEL JF16M dataset](https://doi.org/10.5281/zenodo.3352357), which shares the 256 panel configuration of the AGIPD.

```
import dxtbx
from dials.array_family import flex
img = dxtbx.load('lyso009a_0087.JF07T32V01_master.h5')

for i in range(img.get_num_images()):
  print (i, flex.sum(img.get_raw_data(i)[0]))
```

On master, 1 process: ~13s
On this PR branch, 1 process: ~20s

On master, 64 processes (mpirun libtbx.python script.py): ~1min50s
On this PR branch, 64 processes: ~1min8s

It's a big difference, one that should only get more substantial as the number of cores increases.  Profiling the code in the 1 process case, the added time is spent in splitting the data in memory:
```
for slices in all_slices:
    subset = data[slices]
```
Pretty sure that invokes a copy.  However, I believe that time is made up for when using 64 processes, because less time is spent in I/O.

Ideal solution?  Probably splitting the data in c++ instead of python, hopefully during the read step by using a magic HDF5 command.  I bet there's a way to create a view onto a dataset that gives us what we want so we can get pre-split data reads without need to do any copies.  Research!

### CODE REVIEW

**Comment by graeme-winter** [comment]
Observations... 

 - HDF5 is known to simply _not work_ in parallel right?
 - "thread safe" in this context is peppering the source code with mutexes
 - MPI HDF5 all reads through one node and distributes?
 - is the time actually spent _reading_ or is the time spent _waiting to read_
 - slicing as part of a read can be done, but only if the image chunks on disk are commensurate 

On a practical note I would suggest taking a step back here and:

 - make a generator of fake data which is kinda like the right shape
 - make readers in Python, C++, whatever which read this in isolation (i.e. outside of a DIALS context) 
 - evaluate _this_ for performance estimations

Your comment above saying that a single process took 20s, MPI processes took much longer raised questions if not alarm bells, but I need to look closer - having this demo code which is independent of all the other baggage here (flex etc.) would make it way easier to actually assess the fundamental question. 

My experience is also that HDF5 files can also be "done in a special way" which mean reading is very expensive, but that may or may not be the issue here. Hard to tell in the context. HDF5 _is_ good at contiguous reads of rectangular data though.

**Comment by dwpaley** [comment]
Here's some more timing information. I added timing to `nexus.dataset_as_flex`. On Cori (NERSC) I read two JF16M images from a Nexus h5 file using 1 through 256 processes at once. For the results without this PR the call times are multiplied by 256 to represent reading a full image. These are the results without and with this PR:

image

The improvement is around 3-5x. Anecdotally in recent experience processing big h5 files on many ranks, I've seen >50% of the total stills_process runtime spent in `dataset_as_flex`, so a 3-5x improvement there would be very impactful.

**Comment by dwpaley** [comment]
With the lysozyme data from Zenodo downloaded and assembled:

```
$ cat > do_test.py
from dxtbx.model.experiment_list import ExperimentListFactory
import sys

expts = ExperimentListFactory.from_filenames([sys.argv[1]])
expts[0].imageset.get_mask(0)

$ python do_test.py lyso009a_0087.JF07T32V01_master.h5
Traceback (most recent call last):
  File "/net/dials/raid1/dwpaley/contiguous_nexus/do_test.py", line 5, in <module>
    expts[0].imageset.get_mask(0)
RuntimeError: dxtbx Internal Error: /dev/shm/dwpaley/20210607/modules/dxtbx/imageset.h(837): DXTBX_ASSERT(m1.accessor().all_eq(m2.accessor())) failure.

**Comment by ndevenish** [comment]
Non-draft pending checks against the possible issues that @dwpaley has raised, and checking for no-contiguous cases

**Comment by phyy-nx** [comment]
Current thought is to close this.  @dwpaley and @irisdyoung have a new solution suitable for FormatNXmx that will be prepared over the next week

**Pull request closed without merging**
