### PR TITLE
Deprecate datablock.*Diff pseudoclasses

### PR DESCRIPTION
**Pull request by Anthchirp**
`BeamDiff`, `ScanDiff`, `GoniometerDiff`, `DetectorDiff`, `SequenceDiff` in `dxtbx.datablock` are replaced by functions in `dxtbx.model.compare` (`beam_diff`, etc.)

They don't really have anything to do with datablocks or experiment lists.

### CODE REVIEW

**Comment by Anthchirp** [comment]
Question here: There are a bunch more of these comparator "classes" (`BeamDiff`, `ScanDiff`, `GoniometerDiff`, `DetectorDiff`) in `dxtbx.datablock`. Should these go into `dxtbx.model.experiment_list`, or elsewhere collectively, eg. `dxtbx.model.compare`?

They don't really have anything to do with datablocks or experiment lists.

**Comment by phyy-nx** [comment]
Looks like no impact on my side if these classes are moved.

**Comment by Anthchirp** [comment]
@graeme-winter You self-requested a review on this, I remember it had something to do with tolerance phil thingies. Do you want to add your 2p here or is this a separate PR?

Otherwise this here is done - tests pass and everything.

**Comment by graeme-winter** [comment]
> @graeme-winter You self-requested a review on this, I remember it had something to do with tolerance phil thingies. Do you want to add your 2p here or is this a separate PR?
> 
> Otherwise this here is done - tests pass and everything.

```
Warning: Ambiguous parameter definition: wavelength = 0.979499
Best matches:
  input.tolerance.beam.wavelength
  geometry.beam.wavelength
Assuming geometry.beam.wavelength was intended.
```

I think that this did not used to be the case? 🤔

**Comment by graeme-winter** [comment]
> > @graeme-winter You self-requested a review on this, I remember it had something to do with tolerance phil thingies. Do you want to add your 2p here or is this a separate PR?
> > Otherwise this here is done - tests pass and everything.
> 
> ```
> Warning: Ambiguous parameter definition: wavelength = 0.979499
> Best matches:
>   input.tolerance.beam.wavelength
>   geometry.beam.wavelength
> Assuming geometry.beam.wavelength was intended.
> ```
> 
> I think that this did not used to be the case? 🤔

```
Grey-Area override :) $ dials.import ../insu_7_testbeamline_2.nxs origin=-82.7366,77.3027,-332.998
Sorry: Ambiguous parameter definition: origin = -82.7366,77.3027,-332.998
Best matches:
  input.tolerance.detector.origin
  geometry.detector.panel.origin
  geometry.detector.hierarchy.origin
  geometry.detector.hierarchy.group.origin
```

There we go... I think this was what I was meaning - I think this is somewhat related but I am minded to make that a different pull request.

**Review by graeme-winter — APPROVED** [review]
Scanned change set, did not see anything which would make future debuging harder and moving away from pseudoclasses is _always_ a good thing, thank you for the work here. 

Am _slightly_ concerned by use of `functools.partial` as an indicator of poor overall design, but that is out of context for this change set. I will raise an issue with my other concerns as raised in the conversation.

**Pull request merged**
