### PR TITLE
Put walrus operators back in

### PR DESCRIPTION
**Pull request by dwpaley**
As discussed in dials core meeting, py37 compatibility was harder than just walruses because there was also at least one instance of the equals-in-f-string trick. We sorted out our dependency issues by other means, so the walrus PR can be reverted.

### CODE REVIEW

**Comment by graeme-winter** [comment]
I suspect we _could_ just revert the squashed commit on main right? Probably cleaner?

**Comment by ndevenish** [comment]
Yes, a directly pushed revert would be fine

**Comment by dwpaley** [comment]
Ah, alright. Shall I let you handle it? The corresponding dials commit is https://github.com/dials/dials/commit/2ffab21f70625daedc3855260dee41c36120a669.

**Comment by graeme-winter** [comment]
Reverted 2ffab21f70625daedc3855260dee41c36120a669 on main

**Pull request closed without merging**
