### PR TITLE
Construct Experiments directly rather than via DataBlocks

### PR DESCRIPTION
**Pull request by rjgildea**
* Remove some unused methods
* Convert classes to functions where appropriate
* ExperimentListFactory.from_args: remove verbose parameter
* External class to staticmethod of ExperimentListFactory
* DataBlockFactory.from_filenames() now constructed via ExperimentList
* DeprecationWarning for DataBlock
* Update some DataBlock tests to use ExperimentLists instead

### CODE REVIEW

**Comment by rjgildea** [comment]
There are a currently a couple of failing tests:

```
___________________________________________________________________________________ test_average[False] ____________________________________________________________________________________

dials_data = <DataFetcher: /Users/rjgildea/software/cctbx_py3/build/dials_data>
tmpdir = local('/private/var/folders/dr/_bgcxh092cg7pt001tzwvl5c0000gn/T/pytest-of-rjgildea/pytest-172/test_average_False_0'), use_mpi = False

    @pytest.mark.parametrize("use_mpi", [True, False])
    def test_average(dials_data, tmpdir, use_mpi):
        # averager uses cbf handling code in the xfel module
        pytest.importorskip("xfel")
    
        # Only allow MPI tests if we've got MPI capabilities
        if use_mpi:
            pytest.importorskip("mpi4py")
    
        data = os.path.join(
            dials_data("image_examples"),
            "SACLA-MPCCD-run266702-0-subset.h5",
        )
        if use_mpi:
            command = "mpirun"
            mpargs = "-n 2 dxtbx.image_average".split()
        else:
            command = "dxtbx.image_average"
            mpargs = "-n 2".split()
        result = procrunner.run(
            [command] + mpargs + "-v -a avg.cbf -s stddev.cbf -m max.cbf".split() + [data],
            working_directory=tmpdir,
        )
>       assert not result.returncode and not result.stderr
E       assert (not 1)
E        +  where 1 = ReturnObject(args=('dxtbx.image_average', '-n', '2', '-v', '-a', 'avg.cbf', '-s', 'stddev.cbf', '-m', 'max.cbf', '/Use...ctbx/modules/dxtbx/command_line/image_average.py", line 271, in run\n    assert len(imagesets) == 1\nAssertionError\n').returncode

tests/command_line/test_average.py:34: AssertionError
```
and
```
____________________________________________________________________________ test_split_single_image_datablock _____________________________________________________________________________

dials_data = <DataFetcher: /Users/rjgildea/software/cctbx_py3/build/dials_data>
tmpdir = local('/private/var/folders/dr/_bgcxh092cg7pt001tzwvl5c0000gn/T/pytest-of-rjgildea/pytest-172/test_split_single_image_databl0')

    def test_split_single_image_datablock(dials_data, tmpdir):
        tmpdir.chdir()
        pytest.importorskip("h5py")
        sacla_file = os.path.join(
            dials_data("image_examples"),
            "SACLA-MPCCD-run266702-0-subset.h5",
        )
        db = DataBlockFactory.from_filenames([sacla_file])[0]
        assert db.num_images() == 4
        imageset = db.extract_imagesets()[0]
        subset = imageset[2:3]
        subblock = DataBlockFactory.from_imageset(subset)[0]
>       assert subblock.num_images() == 1
E       assert 4 == 1
E        +  where 4 = <bound method DataBlock.num_images of <dxtbx.datablock.DataBlock object at 0x7f90263ea130>>()
E        +    where <bound method DataBlock.num_images of <dxtbx.datablock.DataBlock object at 0x7f90263ea130>> = <dxtbx.datablock.DataBlock object at 0x7f90263ea130>.num_images

/Users/rjgildea/software/cctbx/modules/dxtbx/tests/test_split_singleimage_datablock.py:31: AssertionError
```
I'm not sure quite exactly what they are testing or how to solve them - I'm hoping @phyy-nx would be better placed to answer these questions.

**Comment by graeme-winter** [comment]
Very happy to see this 👍

Appreciate that this is work in progress but this will be a big help in reducing the technical debt in the system

**Comment by rjgildea** [comment]
There are also a couple of instances of `datablock.unique_detectors()` that would need replacing if we are to strip out `DataBlock` entirely:
```
$ find . -name "*.py" -type f | xargs grep unique_detectors
./datablock.py:    def unique_detectors(self):
./datablock.py:        d = list(self.unique_detectors())
./command_line/plot_detector_models.py:            detectors = sum((db.unique_detectors() for db in datablocks), [])
./command_line/display_parallax_correction.py:    detectors = datablocks[0].unique_detectors()
```

**Comment by phyy-nx** [comment]
I have a rewrite of dxtbx.image_average that uses Experiments instead of datablocks.  I can add it do this PR if you'd like.

**Comment by rjgildea** [comment]
> I have a rewrite of dxtbx.image_average that uses Experiments instead of datablocks. I can add it do this PR if you'd like.

That would be great if you could. I suspect there are also some other command line programs in dxtbx that would need similar treatment - I'm not sure if we have test coverage for all of them:

```
$ grep DataBlockFactory command_line/*.py 
command_line/display_parallax_correction.py:from dxtbx.datablock import DataBlockFactory
command_line/display_parallax_correction.py:    datablocks = DataBlockFactory.from_args(args or sys.argv[1:])
command_line/image_average.py:from dxtbx.datablock import DataBlockFactory
command_line/image_average.py:        datablocks = DataBlockFactory.from_filenames([paths[0]])
command_line/image_average.py:        datablocks = DataBlockFactory.from_filenames([iterable[0]])
command_line/plot_detector_models.py:from dxtbx.datablock import DataBlockFactory
command_line/plot_detector_models.py:            datablocks = DataBlockFactory.from_json_file(file_name, check_format=False)
command_line/radial_average.py:                obj = dxtbx.datablock.DataBlockFactory.from_filenames([x])[
command_line/radial_average.py:                    obj = dxtbx.datablock.DataBlockFactory.from_json_file(x)[
```

**Comment by phyy-nx** [comment]
Both tests are fixed.  I'm glad to get this re-write of the image averager in as I've been sitting on it for a few months.  IIRC it uses less memory and runs faster too.  I highly recommend using MPI though when using the averager.  easy_mp just can't compete with MPI reduce.

The main functionality of `test_split_single_image_datablock`, now `test_split_single_image_imageset`, was actually lost in 80ab3372e1b637f65183c6e4054f91532b77a774 (though arguably it didn't matter since datablocks were being phased out), so I've now re-written that test to generally cover what the test used to do.  See #203 for reference.

**Comment by phyy-nx** [comment]
TODO for me:

- [ ] Add test for radial_average and verify it still works in this PR.  May need to re-write radial_average
- [ ] Run xfel_regression on this branch.  There may be some datablocks used in cctbx.xfel.

**Comment by rjgildea** [comment]
@phyy-nx have you managed to run xfel_regression on this PR?

**Comment by phyy-nx** [comment]
Nope, sorry, BioXFEL is this week.  I'll try to get it done soon though.

**Comment by ndevenish** [comment]
This is somewhat more challenging to correctly fix than anticipated - `model/experiment_list.py` merges cleanly but doesn't correctly integrate the urlparse/scheme changes from 1c4b528a6605f0b9979de74373a8d6de3c3e09ea

**Comment by ndevenish** [comment]
I think this is correct - the changes on the main branch in datablock needed to be moved over manually to experiment_list

**Comment by phyy-nx** [comment]
Ok, I've run the xfel_regression tests on this branch, with dials/dials#1570 checked out as well, and `xfel_regression/test/command_line/tst_cxi_formatXTC.py` is failing because it still uses datablocks.  But it's failing in a way that's unexpected:

```
    Traceback (most recent call last):
      File "/dev/shm/aaron/cctbx/modules/xfel_regression/test/command_line/tst_cxi_formatXTC.py", line 105, in <module>
        tester.run_all()
      File "/dev/shm/aaron/cctbx/modules/xfel_regression/test/command_line/tst_cxi_formatXTC.py", line 97, in run_all
        self.test_cxid1916()
      File "/dev/shm/aaron/cctbx/modules/xfel_regression/test/command_line/tst_cxi_formatXTC.py", line 76, in test_cxid1916
        datablocks_cbf = DataBlockFactory.from_filenames(flist_sorted)
      File "/dev/shm/aaron/cctbx/modules/dxtbx/datablock.py", line 773, in from_filenames
        datablocks.extend(format_expts.to_datablocks())
      File "/dev/shm/aaron/cctbx/modules/dxtbx/model/__init__.py", line 708, in to_datablocks
        imageset["images"], imageset["single_file_indices"]
    KeyError: 'single_file_indices'
```
I could re-write the test but doesn't this mean something else is wrong?

**Comment by rjgildea** [comment]
Can we merge this in, as @ndevenish would like to get changes in soon in preperation for the dials 3.4 release.

I attempted to run the failing test, however it depends on psana, which I didn't fancy attempting to install on my mac development environment (I don't even know if this is possible). Given that we want to deprecate/remove `DataBlock` anyway, and this test is apparently using functionality that isn't covered by dxtbx or dials tests, I suggest that time would be better spent modifying the failing test to use `Experiment`s.

**Comment by ndevenish** [comment]
Okay, so looking at this stack trace, 
```
      File "/dev/shm/aaron/cctbx/modules/dxtbx/datablock.py", line 773, in from_filenames
        datablocks.extend(format_expts.to_datablocks())
      File "/dev/shm/aaron/cctbx/modules/dxtbx/model/__init__.py", line 708, in to_datablocks
        imageset["images"], imageset["single_file_indices"]
    KeyError: 'single_file_indices'
```
This looks somewhat like an actual bug - since we're going via imageset in [dictionary](https://github.com/cctbx/dxtbx/blob/1d98bcbfa782e9b7bb93261d218a813e3221a143/model/__init__.py#L689-L690) form, `single_file_indices` is only created as part of an imageset dictionary if it's being created from a `FormatMultiImage`
https://github.com/cctbx/dxtbx/blob/1d98bcbfa782e9b7bb93261d218a813e3221a143/model/__init__.py#L644-L645
Suggesting that this will always be missing if created with single-image files e.g. CBF? However, this suggests that lots more tests should break. How exhaustively is the `to_datablock` function tested - ideally it'd be used in every single existing datablock test. I can't remember where we fell on datablock backwards compatibility.

However, if I'm right about the cause of this, the fix looks reasonable enough; The "image" field is apparently expected to be missing when it doesn't apply - see
https://github.com/cctbx/dxtbx/blob/1d98bcbfa782e9b7bb93261d218a813e3221a143/datablock.py#L620-L623
so - changing `imageset["single_file_indices"]` to `imageset.get("single_file_indices")` and wrapping the assignment in an if test:
```python
if file_index is not None:
    image_dict["image"] = file_index
```
should be sufficient to preserve the previous behaviour?

**Comment by ndevenish** [comment]
Also an additional note that fixing the merge conflicts and validating them for this is getting pretty time-consuming to resolve, so yes I'd love to get this in for 3.4 ([next week](https://github.com/dials/dials/wiki/Version-Release-History)) if at all possible!

**Comment by dwpaley** [comment]
Hi, sorry for the delay on this reproducer that I promised. I grabbed one of the test images (which are dumped into a temp folder using `cctbx.xfel.xtc_process`) and put it on my personal dropbox for expediency's sake. This will reproduce the crash with dxtbx on this branch and dials on branch dxtbx-no-datablock:

```
wget https://www.dropbox.com/s/pn33aele94zxycv/img.cbf
libtbx.python -c "from dxtbx.datablock import DataBlockFactory; \
  DataBlockFactory.from_filenames(['img.cbf']) "
```

**Comment by ndevenish** [comment]
This looks better now - I intend to merge in tomorrow

**Pull request merged**
