### PR TITLE
NeXus: avoid unnecessarily walking the full tree

### PR DESCRIPTION
**Pull request by rjgildea**
When extracting objects from a NeXus file, it isn't necessary to walk the full tree multiple times.

E.g. the NXentry class should be at the top level of the file, not arbitrarily nested. Similarly, NXbeam should be a child node of the NXinstrument or NXsamples groups etc.

Also add some tests for the expected behaviour of the `nexus.find_entries` and `nexus.find_class` functions.

This PR shaves ~70% of the runtime off constructing 

With master:
```
$ dials.python time_format_class.py $(dials.data get -q vmxi_thaumatin)/image_15799_master.h5
9.3881 seconds (0.0939 seconds per image)
```
With this PR:
```
$ dials.python time_format_class.py $(dials.data get -q vmxi_thaumatin)/image_15799_master.h5
2.7626 seconds (0.0276 seconds per image)
```

For #276

### CODE REVIEW

**Comment by graeme-winter** [comment]
Without looking at the code changes yet am very supportive of you looking at this thank you. The tree walking looks expensive & this is a pretty useful speedup you demonstrate. Would be curious to see impact on importing larger files etc...

**Comment by rjgildea** [comment]
One thing to note is that this PR (currently) doesn't support [`NXsubentry`](https://manual.nexusformat.org/classes/base_classes/NXsubentry.html#nxsubentry). I don't know if `NXsubentry` is ever used within any known NXmx use cases, but it should be relatively trivial to add support - it would just require an additional level of iteration over the children of any `NXentry` objects to find any `NXsubentry` objects.

**Comment by phyy-nx** [comment]
Super cool.  I also haven't reviewed the changes but would like to when this PR graduates from draft status.

I tested it on the [SwissFEL JF16M dataset](https://doi.org/10.5281/zenodo.3352357):
```
dials.stills_process lyso009a_0087.JF07T32V01_master.h5 max_images=1 find_spots=False
```
It ran in 5 seconds instead of 10 and diffing the imported.expt between master and the nexus_find_entries branch shows no differences.

**Review by benjaminhwilliams — CHANGES_REQUESTED** [review]
I notice we call `find_class` three times on the same handle each time we initialise either an `NXinstrument` or a `NXmxEntry`.  Obviously, this means performing the same iteration three times over all the children of that node.  I had a go at modifying `find_class` so that it optionally accepts multiple `nx_class` names and searches for them all in a single iteration.  Using your test case, it seems to save me an additional 10% of the already reduced run time.

With my changes:
```
$ dials.python time_format_class.py $(dials.data get -q vmxi_thaumatin)/image_15799_master.h5
1.5693 seconds (0.0157 seconds per image)
```

Without:
```
$ dials.python time_format_class.py $(dials.data get -q vmxi_thaumatin)/image_15799_master.h5
1.7475 seconds (0.0175 seconds per image)
```
The diff is https://github.com/cctbx/dxtbx/commit/4a95d69f8ecc0f52178c81edc5778893fe7b81c5, and I can merge it into the PR branch if you want.

The downside is that the conditional return statement is a little cumbersome.  To avoid this, I tried changing the signature so that it always returns a tuple of lists, but in the majority of cases when you're only looking for a single `NXclass`, that just makes it confusingly idiosyncratic.  So I think the above diff is my best stab.

**Comment by rjgildea** [comment]
> I notice we call `find_class` three times on the same handle each time we initialise either an `NXinstrument` or a `NXmxEntry`. Obviously, this means performing the same iteration three times over all the children of that node. I had a go at modifying `find_class` so that it optionally accepts multiple `nx_class` names and searches for them all in a single iteration. Using your test case, it seems to save me an additional 10% of the already reduced run time.
> 
> With my changes:
> 
> ```
> $ dials.python time_format_class.py $(dials.data get -q vmxi_thaumatin)/image_15799_master.h5
> 1.5693 seconds (0.0157 seconds per image)
> ```
> 
> Without:
> 
> ```
> $ dials.python time_format_class.py $(dials.data get -q vmxi_thaumatin)/image_15799_master.h5
> 1.7475 seconds (0.0175 seconds per image)
> ```
> 
> The diff is [4a95d69](https://github.com/cctbx/dxtbx/commit/4a95d69f8ecc0f52178c81edc5778893fe7b81c5) and I can merge it into the PR branch if you want.
> 
> The downside is that the conditional return statement is a little cumbersome. To avoid this, I tried changing the signature so that it always returns a tuple of lists, but in the majority of cases when you're only looking for a single `NXclass`, that just makes it confusingly idiosyncratic. So I think the above diff is my best stab.

I would be tempted to err on the side of merging the existing PR as is (unless there are any fundamental issues with it) and then submit your suggestions as an additional PR on top of that - there are almost certainly many further opportunities for performance improvements within `nexus.py` and this PR is only the beginning, rather than a complete solution. Open to other opinions, however.

**Comment by rjgildea** [comment]
@phyy-nx have you had chance to review this PR? It would deliver some real performance improvements to our per-image analysis code running on the beamlines, so it would be good to get this merged ASAP.

**Comment by phyy-nx** [comment]
Hi, thanks for the bump.  I'll review it today.

**Review by phyy-nx — APPROVED** [review]
Looks good to me.  Thanks.

**Comment by benjaminhwilliams** [comment]
> I would be tempted to err on the side of merging the existing PR as is (unless there are any fundamental issues with it) and then submit your suggestions as an additional PR on top of that - there are almost certainly many further opportunities for performance improvements within `nexus.py` and this PR is only the beginning, rather than a complete solution. Open to other opinions, however.

Sounds sensible to me.  Sorry if you've been waiting for my reply.

**Review by benjaminhwilliams — APPROVED** [review]

**Review by noemifrisina — APPROVED** [review]

**Pull request merged**
