### PR TITLE
dlsnxs2cbf: support phi scans

### PR DESCRIPTION
**Pull request by rjgildea**

### CODE REVIEW

**Comment by benjaminhwilliams** [comment]
Thanks @rjgildea, this is super helpful.  I will augment this a little to allow arbitrary 2θ and to correct the detector ID and then we have most Diamond use cases covered.

**Comment by rjgildea** [comment]
> Thanks @rjgildea, this is super helpful. I will augment this a little to allow arbitrary 2θ and to correct the detector ID and then we have most Diamond use cases covered.

It might be useful to add a suitable I19-2 dataset to dials_data so we can add a test case if you have the time/inclination.

**Comment by benjaminhwilliams** [comment]
And I need to make it support κ geometry.  But still, this is useful impetus, thank you.

**Comment by graeme-winter** [comment]
So, my understanding is that this will not support the full geometry stack? It is just generating the "mini" CBF? Or I have missed something?

**Comment by benjaminhwilliams** [comment]
> So, my understanding is that this will not support the full geometry stack? It is just generating the "mini" CBF? Or I have missed something?

I couldn't tell you — I know that there are such things as 'mini-CBF' and 'full CBF', but I wouldn't necessarily be able to tell them apart if you put them in front of me, unless the differences are very obvious.  I can't tell from the `dlsnxs2cbf` code, for example, what flavour is being written.

**Comment by ndevenish** [comment]
My understanding was that the CBF written with the data in "Comment fields" e.g.
```
    result.append("# Threshold_setting: 0 eV")
    result.append("# Gain_setting: mid gain (vrf = -0.200)")
    result.append("# N_excluded_pixels = 0")
```
and then scraped back again were miniCBF files.

What's the status of this PR; @benjaminhwilliams did you finish your augmentations?

**Comment by benjaminhwilliams** [comment]
> What's the status of this PR; @benjaminhwilliams did you finish your augmentations?

I need to write new tests.  The collection data for those tests is scheduled for next Wednesday.  This will also now depend on #460, which likewise needs tests with new data.

All in all, this PR should probably be marked as a draft for now.

**Comment by ndevenish** [comment]
After discussion we'd like to get this in here for this run now, so that we can test and refine against live data. Tests will follow once we know that it's working for its intended purpose.

**Pull request merged**
