### PR TITLE
Remove unnecessary format subclass methods

### PR DESCRIPTION
**Pull request by rjgildea**
Remove unnecessary `__init__` and `_start` methods from Format classes:

- There is no need for every subclass to redefine the `__init__` method and
call its parent's `__init__` method. As well as a lot of unnecessary code
duplication, this also led to the subclass `self.understand()` method
being called once for every class in the format class hierarchy.
- There is no need for every subclass to redefine the `_start()` method and
call its parent's `_start()` method.
- Use `super()` where applicable.

### CODE REVIEW

**Comment by graeme-winter** [comment]
Reviewing...

**Comment by graeme-winter** [comment]
0-th order - tests:

Master:

```
Results (47.73s):
     504 passed
       1 xfailed
      15 skipped
```

Branch:
```
Results (117.56s):
     503 passed
       1 xfailed
      15 skipped
```

Interesting that there were fewer tests 🤔 possibly one added since you made the branch. Time difference due to nproc= for first not second 🙄

**Comment by graeme-winter** [comment]
I should also say: this is a _good thing_ and will help newer developers as there is (slightly less) cargo culted nonsense in there.

**Comment by rjgildea** [comment]
> Interesting that there were fewer tests 🤔 possibly one added since you made the branch.
@Anthchirp split one test into two here which probably accounts for the differing number of test compared to master: https://github.com/dials/dxtbx/commit/8c169ffb7d5a491af4c35e427a3fe13e3b14142a

**Comment by Anthchirp** [comment]
I now removed one on master, so count should be identical again :smirk:

**Pull request merged**
