### PR TITLE
Redo the ImageSetData class to use less memory

### LINKED ISSUE #437: Sliced ImageSets use too much memory
At the moment, when creating an ImageSet that represents a slice of a multi-image datafile, the Reader object that [is created](https://github.com/cctbx/dxtbx/blob/main/src/dxtbx/imageset.h#L172) to hold the arrays of dxtbx models [is of size](https://github.com/cctbx/dxtbx/blob/main/src/dxtbx/format/FormatMultiImage.py#L150) `max(single_file_indices)` instead of size `len(single_file_indices)`.  This leads to huge arrays with only one item for stills.

For example, if I have an hdf5 file with 10 images, and I an equivalent imageset for it, and I slice it like this:

```
subset = imageset[5:6]
```

Then `single_file_indices` will be the array `[5]`, but the `ImageSetData` object will have a [list of models](https://github.com/cctbx/dxtbx/blob/main/src/dxtbx/imageset.h#L172) with 6 items, the first 5 of which will be empty.

### PR DESCRIPTION
**Pull request by phyy-nx**
This change alters ImageSetData to keep its models in an array of len(indices) instead of len(max(indices)).  Concurrently, whenever the imageset dereferences a model, it needs to not dereference the indices array.  Retain dereferencing the indices array when reading the data.

Mostly untested.  Needs review and likely further work.  Work in progress.

Closes #437

### CODE REVIEW

**Comment by phyy-nx** [comment]
Note, as part of working on this changeset I created a combined experiment list with 10 experiments drawn from a single SwissFEL data file with over a thousand images.  Normally, the combined experiment list would have 10 imagesets in it and be very slow to load.  Compared to the single image case with takes 20 seconds, this takes 2 minutes to load in the image viewer.

I then made a version with 10 experiments and a single imageset, where that imageset had single_file_indices set to an array of 10 (disjoint) image indices.  Indeed, it only took 20 seconds to load.  It's definitely where we need to go for processing stills.

**Comment by phyy-nx** [comment]
Alternative version on branch [`sfi_redo2`](https://github.com/cctbx/dxtbx/tree/sfi_redo2) using maps for the ImageSetData model arrays.  Also not working yet.

**Comment by dwpaley** [comment]
Looking into these test failures. Here's a simple snippet. (must run `pytest --regression $MODULES/dxtbx/tests/test_imageset.py::test_single_file_indices` first to get the test image)

```
$ cd $BUILD/dials_data/image_examples
$ cat > repro.py
import dxbtx.format
fname = 'SACLA-MPCCD-run266702-0-subset.h5'
format_class=dxtbx.format.Registry.get_format_class_for_file(fname)
iset = format_class.get_imageset([fname], single_file_indices=None, lazy=False)

$ libtbx.python repro.py
Traceback (most recent call last):
  File "repro.py", line 4, in <module>
    iset = format_class.get_imageset([fname], single_file_indices=None, lazy=False)
  File "/dev/shm/dwpaley/20211104/modules/dxtbx/src/dxtbx/format/FormatMultiImageLazy.py", line 42, in get_imageset
    lazy=lazy,
  File "/dev/shm/dwpaley/20211104/modules/dxtbx/src/dxtbx/format/FormatMultiImage.py", line 240, in get_imageset
    reader=reader, masker=None, vendor=vendor, params=params, format=cls
Boost.Python.ArgumentError: Python argument types in
    ImageSetData.__init__(ImageSetData)
did not match C++ signature:
    __init__(boost::python::api::object, boost::python::api::object reader, boost::python::api::object masker, std::string template='', std::string vendor='', boost::python::dict params=None, boost::python::api::object format=None)
    __init__(boost::python::api::object, boost::python::api::object reader, boost::python::api::object masker)

```

@phyy-nx, just checking, can you confirm this is supposed to still work?

**Comment by dwpaley** [comment]
I've done some testing of memory usage by loading one of three expt files which contain 1, ~25 and ~400 single-image imagesets and comparing heap usage before/after.

Main branch:
1 expt: 28 kB
25 expts: 5.5 MB
400 expts: 58.5 MB

This branch:
1 expt: 14 kB
25 expts: 312 kB
400 expts: 4.2 MB

On the main branch, for each imageset, four large-ish chunks are allocated on the heap. It looks like this:
```
 0x000055bb02d16670 -> 0x000055bb02d2b4df    85616 bytes uncategorized::85616 bytes |....................|
    0x000055bb02d2b4e0 -> 0x000055bb02d4034f    85616 bytes uncategorized::85616 bytes |....................|
    0x000055bb02d40350 -> 0x000055bb02d551bf    85616 bytes uncategorized::85616 bytes |....................|
    0x000055bb02d551c0 -> 0x000055bb02d6a02f    85616 bytes uncategorized::85616 bytes |....................|
    0x000055bb02d6a030 -> 0x000055bb02d6b51f     5360 bytes uncategorized::5360 bytes |....................|
    0x000055bb02d6b520 -> 0x000055bb02d6b55f       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02d6b560 -> 0x000055bb02d6b59f       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02d6b5a0 -> 0x000055bb02d6b5df       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02d6b5e0 -> 0x000055bb02d6b61f       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02d6b620 -> 0x000055bb02d6b65f       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02d6b660 -> 0x000055bb02d6b68f       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02d6b690 -> 0x000055bb02d6b6cf       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02d6b6d0 -> 0x000055bb02d6b6ef       32 bytes uncategorized::32 bytes |...........I... ...|
    0x000055bb02d6b6f0 -> 0x000055bb02d6b72f       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02d6b730 -> 0x000055bb02d6b76f       64 bytes uncategorized::64 bytes |..cdxtbx.format.Form|
    0x000055bb02d6b770 -> 0x000055bb02d6b99f      560 bytes uncategorized::560 bytes |`c.?.....>6.......|
    0x000055bb02d6b9a0 -> 0x000055bb02d6b9df       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02d6b9e0 -> 0x000055bb02d6ba1f       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02d6ba20 -> 0x000055bb02d6ba3f       32 bytes uncategorized::32 bytes |.a.?...........p...|
    0x000055bb02d6ba40 -> 0x000055bb02d6ba7f       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02d6ba80 -> 0x000055bb02d6babf       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02d6bac0 -> 0x000055bb02d6baff       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02d6bb00 -> 0x000055bb02d6bb2f       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02d6bb30 -> 0x000055bb02d6bb5f       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02d6bb60 -> 0x000055bb02d6bb8f       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02d6bb90 -> 0x000055bb02d6bbbf       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02d6bbc0 -> 0x000055bb02d6bbef       48 bytes   C:string data:None |1d5cb002-249a-4a84-a|
    0x000055bb02d6bbf0 -> 0x000055bb02d6bc1f       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02d6bc20 -> 0x000055bb02d6bc4f       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02d6bc50 -> 0x000055bb02d6bc7f       48 bytes   C:string data:None |bd770f1e-d5b6-4461-a|
    0x000055bb02d6bc80 -> 0x000055bb02d6bcaf       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02d6bcb0 -> 0x000055bb02d81cff    90192 bytes uncategorized::90192 bytes |....................|
    0x000055bb02d81d00 -> 0x000055bb02d97d4f    90192 bytes uncategorized::90192 bytes |....................|
    0x000055bb02d97d50 -> 0x000055bb02dadd9f    90192 bytes uncategorized::90192 bytes |....................|
    0x000055bb02dadda0 -> 0x000055bb02dc3def    90192 bytes uncategorized::90192 bytes |....................|
    0x000055bb02dc3df0 -> 0x000055bb02dc53ff     5648 bytes uncategorized::5648 bytes |....................|
    0x000055bb02dc5400 -> 0x000055bb02dc543f       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02dc5440 -> 0x000055bb02dc547f       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02dc5480 -> 0x000055bb02dc54bf       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02dc54c0 -> 0x000055bb02dc54ff       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02dc5500 -> 0x000055bb02dc553f       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02dc5540 -> 0x000055bb02dc556f       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02dc5570 -> 0x000055bb02dc55af       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02dc55b0 -> 0x000055bb02dc55cf       32 bytes uncategorized::32 bytes |...........I... ...|
    0x000055bb02dc55d0 -> 0x000055bb02dc560f       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02dc5610 -> 0x000055bb02dc564f       64 bytes uncategorized::64 bytes |..cdxtbx.format.Form|
    0x000055bb02dc5650 -> 0x000055bb02dc587f      560 bytes uncategorized::560 bytes |`c.?.....>6.......|
    0x000055bb02dc5880 -> 0x000055bb02dc58bf       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02dc58c0 -> 0x000055bb02dc58ff       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02dc5900 -> 0x000055bb02dc591f       32 bytes uncategorized::32 bytes |.a.?...........PV..|
    0x000055bb02dc5920 -> 0x000055bb02dc595f       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02dc5960 -> 0x000055bb02dc599f       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02dc59a0 -> 0x000055bb02dc59df       64 bytes uncategorized::64 bytes |.H.G...............|
    0x000055bb02dc59e0 -> 0x000055bb02dc5a0f       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02dc5a10 -> 0x000055bb02dc5a3f       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02dc5a40 -> 0x000055bb02dc5a6f       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02dc5a70 -> 0x000055bb02dc5a9f       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02dc5aa0 -> 0x000055bb02dc5acf       48 bytes   C:string data:None |8d3076c5-03c8-43fc-b|
    0x000055bb02dc5ad0 -> 0x000055bb02dc5aff       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02dc5b00 -> 0x000055bb02dc5b2f       48 bytes uncategorized::48 bytes |...G...............|
    0x000055bb02dc5b30 -> 0x000055bb02dc5b5f       48 bytes   C:string data:None |4c69c301-71e7-4d55-b|
    0x000055bb02dc5b60 -> 0x000055bb02dc5b8f       48 bytes uncategorized::48 bytes |...G...............|
```
Reading down the heap addresses in order, the sizes of the 4 large objects grow up to ~100 kB, then reset to a few kB, then grow again. I can't see specifically what is there, but it becomes quite a lot. This is no longer observed with this PR.

Would welcome any other suggestions for assessing the memory usage, but I hope it's clear enough that the improvement here is pretty big.

dxtbx and xfel_regression tests all pass. @graeme-winter, any suggestion for who could review this?

**Comment by dwpaley** [comment]
The four large objects are these ones allocated in the ImageSetData constructor, I believe @phyy-nx already appreciated this through an unusual technique of "understanding the code" :)
```
class ImageSetData {
[...]
ImageSetData(boost::python::object reader, masker_ptr masker)
    : reader_(reader),
      masker_(masker),
      beams_(boost::python::len(reader)),
      detectors_(boost::python::len(reader)),
      goniometers_(boost::python::len(reader)),
      scans_(boost::python::len(reader)),
      reject_(boost::python::len(reader)) {}
[...]
scitbx::af::shared<beam_ptr> beams_;
scitbx::af::shared<detector_ptr> detectors_;
scitbx::af::shared<goniometer_ptr> goniometers_;
scitbx::af::shared<scan_ptr> scans_;
}
```

**Comment by dwpaley** [comment]
Note that the large chunks allocated on the heap are each 16 bytes x the length of the Reader that was used to construct the ImageSetData. Thus a chunk of size 78592 corresponds to an `af::shared<boost::shared_ptr<BeamBase> >` with 4911 entries, and therefore came from an experiment with single_file_indices [4910]. The shared_ptr just contains two 64-bit pointers as described here: https://en.cppreference.com/w/cpp/memory/shared_ptr, but it adds up because we're unnecessarily storing many thousands of them.

**Comment by ndevenish** [comment]
This was agreed to be merged at the [2021-12-09](https://dials.github.io/kb/core/20211209) DIALS core meeting. However, I'm reluctant to merge this in right before a release, so shall merge this once 3.8 is out.

**Comment by ndevenish** [comment]
Since this is quite a significant change, I realised @dwpaley that you weren't in the AUTHORS list in dxtbx, so I added it. Please let me know if this isn't okay.

Otherwise, I intend to merge this tomorrow morning.

**Comment by dwpaley** [comment]
Not a problem of course :) Thanks!

**Pull request merged**
