### PR TITLE
Don't apply a new rotation three times

### PR DESCRIPTION
**Pull request by benjaminhwilliams**
`dxtbx.model.Goniometer.rotate_around_origin` appears to have incorrect behaviour.  If we are trying to rotate the goniostat rotation operator _R_ = _S_ ∘ _R'_ ∘ _F_ by a new rotation _N_, it is not correct to rotate all three components _S_, _R'_ & _F_ by _N_:
- _N_ ∘ _R_ = _N_ ∘ _S_ ∘ _R'_ ∘ _F_,                ← (we should do this)
- _N_ ∘ _R_ ≠ (_N_ ∘ _S_) ∘ (_N_ ∘ _R'_) ∘ (_N_ ∘ _F_).  ← (previously, we did this)

### CODE REVIEW

**Comment by benjaminhwilliams** [comment]
This behaviour didn't have a test, and I haven't yet added one.  I think that would be a valuable exercise, but I'd like a little input first from someone who has recently tried using this method in anger (@dagewa perhaps?), to check I have my facts straight.

**Comment by dagewa** [comment]
Your solution suggests I was trying to use this method incorrectly. In https://github.com/dials/dials_scratch/blob/master/command_line/convert_to_XDS_frame.py I want to convert an experiment from its expression using the dxtbx default coordinate system to a different coordinate system. In that case, I am "rotating the world" rather than rotating the objects in it. For the other models, the `rotate_around_origin` method seems sufficient for this, but for the more complicated goniometer model I think I can't use this for that purpose. I can see that because this method does not change the datum axis, but if I was rotating the world to a new coordinate system, I would expect that to change.

So, I suppose this solution is correct, but its purpose is limited to rotating the goniometer axis _within_ a particular coordinate system. Does that make sense?

**Comment by benjaminhwilliams** [comment]
Ah, I see.  I haven't used the `rotate_around_origin` methods before, so I hadn't clocked that they are really intended to facilitate a rotation of the basis.  If that is the case, and if the effect of `scitbx.array_family.flex.vec3_double.rotate_around_origin` is to rotate a vector _v_ by a rotation _N_ (i.e. _v_ ↦ _N_ ∘ _v_), then perhaps the `dxtbx.model.Goniometer.rotate_around_origin` ought to be doing this?
_R_ ↦ _N_ ∘ _R_ ∘ _N_ ⁻¹ = (_N_ ∘ _S_ ∘ _N_ ⁻¹) ∘ (_N_ ∘ _R'_ ∘ _N_ ⁻¹) ∘ (_N_ ∘ _F_ ∘ _N_ ⁻¹)

**Comment by elena-pascal** [comment]
Isn't it a passive rotation, so just transposed?

**Comment by dagewa** [comment]
Hi @benjaminhwilliams I don't think they really were intended to facilitate a rotation of the basis, but I was using them to implicitly do so. Ideally, a basis change would be implemented at the Experiment level, so that all models are updated accordingly. That is probably a bit too much work when the use case is just a script I put in `dials_scratch/`

**Review by elena-pascal — APPROVED** [review]
yes please

**Pull request merged**
