### PR TITLE
Stills process py3

### PR DESCRIPTION
**Pull request by phyy-nx**
As part of the psana1/psana2/python3 work, we have now reached the point where we need to convert the cbf writing in cctbx.xfel to python 3.  It became clear that it makes sense to move all the string handling into a centralized class in dxtbx, `cbf_wrapper`, that wraps the pycbf swig code.  We are using the py2/py3 aware to_str and to_bytes functions @bkpoon made in libtbx to do the conversion in the wrapping class.  What's nice is all the `b"` tags now can go away in the FormatCBFFull classes.

A subsequent pull request in cctbx_project/xfel will be prepared to use these features.

### CODE REVIEW

**Comment by Anthchirp** [comment]
I feel that using the `to_str` and `to_bytes` functions needlessly blurs the distinction between binary and text data again. It makes it harder to understand what is going on and encourages not treating data correctly in the first place.
For example the `to_bytes` function is very difficult to explain and even harder to understand. By virtue of being a "general unicode handling" function it makes a number of assumptions, and I do not believe these to be appropriate. For example `to_bytes` assumes a [different default codec](https://github.com/cctbx/cctbx_project/blob/bdf4be82e332d833b11c364706713cd59b5e387f/libtbx/utils.py#L2415-L2418) on Windows (MBCS) to Linux (utf-8). The function also [raises `Sorry()`](https://github.com/cctbx/cctbx_project/blob/bdf4be82e332d833b11c364706713cd59b5e387f/libtbx/utils.py#L2427) which is [not helpful](https://github.com/dials/dials/issues/729#issuecomment-471963574) in a function that is not even close to user-facing.

I would very much prefer explicit data types and explicit conversions. There will always be `b""` strings in dxtbx format classes - as that is what dxtbx format classes do.

`cbf_wrapper` is a misnomer, as it is subclassing pycbf_handle_struct. This is asking for trouble if the API ever changes, and I believe the code could be a lot simpler and easier to read if it was an actual wrapper class.

**Comment by phyy-nx** [comment]
Hi, some responses:

While we have py2 and py3 cross-compatibility, because of PEP 529, we have to use MBCS on windows to handle unicode filenames.  (See https://www.python.org/dev/peps/pep-0529/).  That's why it's in to_bytes.  Using a library function that is smart about stuff like this is, to me, a good thing.

I do think not using Sorry in to_bytes/to_str would be reasonable.  I think Sorry is used for phenix UI reasons, but an issue/pull request in cctbx on the topic would be fine.  Maybe a switch to change the exception behavior?

Explicit conversions are wordy.  I'd rather hide them in function calls, hence this wrapper.  That way the Format class does it work in a clean way, with boiler plate hidden in another file.

Renaming the class is fine if you have a suggestion.  It's interesting that cbf_detector_wrapper in the new code probably fits your definition as it doesn't subclass.

**Comment by graeme-winter** [comment]
Comments limited to FormatCBFFull / areas which are related to _reading_ full CBF files. 

I have to say that I am not keen on adding "convenience layers" like this to simplify support for an obsolete version of Python, simply because I can look at myself in two years time trying to debug something and finding that the `cbf_wrapper` is doing something I don't want / understand & I won't be able to fix it [1] - at the moment if there is a change in the PyCBF API for whatever reason I can follow the logic directly. 

I am also looking forwards rather than backwards, and so am not keen to jump through hoops to support Python 2.7 [2] without making it easy to sanitise the code in a future revision where we actively drop 2.7. Once this `cbf_wrapper` layer is there, it will be mandatory for all time. In particular, I am looking to a time when pycbf is Python 3 only & gracefully handles all the string mapping itself. 

Given that the code as it was worked fine with Python 2.7 and 3.x I'm not convinced by the need for this. I am also very nervous about "Maybe a switch to change the exception behavior?" depending on whether in a DIALS or PHENIX environment, and 100% support the idea that we do _not_ raise `Sorry` in a library environment. 

Since I found a counterexample to this statement I have made an issue to that effect:

https://github.com/cctbx/dxtbx/issues/138

N.B. I do not apply these comments to use in e.g. `FormatCBFMultiTileHierarchy.py` 

[1] e.g. will face something like https://github.com/cctbx/cctbx_project/issues/419#issuecomment-558485672

[2] though I recognise the need for longer term support for dxtbx on Python 2.7 in master than e.g. DIALS.

**Comment by graeme-winter** [comment]
Have now removed almost all Sorry from everywhere but command_line.

**Comment by Anthchirp** [comment]
Going back to the point I raised about encoding:
> For example the `to_bytes` function is very difficult to explain and even harder to understand.
> By virtue of being a "general unicode handling" function it makes a number of assumptions, and I
> do not believe these to be appropriate. For example `to_bytes` assumes a [different default codec](https://github.com/cctbx/cctbx_project/blob/bdf4be82e332d833b11c364706713cd59b5e387f/libtbx/utils.py#L2415-L2418)
> on Windows (MBCS) to Linux (utf-8). 

@phyy-nx replied:
> While we have py2 and py3 cross-compatibility, because of PEP 529, we have to use MBCS on
> windows to handle unicode filenames. (See https://www.python.org/dev/peps/pep-0529/). That's
> why it's in to_bytes. Using a library function that is smart about stuff like this is, to me, a good
> thing.

The issue I have with this is that I believe that this 'smart' action is completely inappropriate. I may be barking up the wrong tree entirely, but most `to_bytes()` calls appear to me to have nothing to do with filenames. Two excerpts from the pull request:
```python
        """Create a new category and populate it with column names"""
        self.new_category(to_bytes(name))
        for column in columns:
            self.new_column(to_bytes(column))

(...)

    def get_axis_offset(self, axis_id):
        return super(cbf_wrapper, self).get_axis_offset(to_bytes(axis_id))
```
None of these are _filenames_?

Now it may well be that the pycbf/cbflib API expects a different encoding on Linux vs Windows _in general_ and I'm just ignorant of this fact. If that is not the case though then the only alternatives that I can see are that this
1. produces different output on different platforms,
2. produces identical output but only because the actually used character set is small (think: UTF-8 vs ASCII), or
3. produces identical output with arbitrary input.

Out of those 1. is what I'm worried about, 2. is an encoding bug, and 3. means the encoding step is needlessly complex.

**Comment by phyy-nx** [comment]
Folks, I'm out of the country on a beam time and can't respond, but this pull request is needed for a DOE milestone due pretty soon.  If @graeme-winter and @Anthchirp want to re-write it, please feel free, but please do so soon?  When that's done, we will sync the relevant cctbx branch so we can do our cbf writing in python 3.

@graeme-winter Having the py3 conversion code in a separate location makes dropping it easier if/when pycbf is ever py3/unicode aware, right?

**Comment by graeme-winter** [comment]
> @graeme-winter Having the py3 conversion code in a separate location makes dropping it easier if/when pycbf is ever py3/unicode aware, right?

Nope, it adds an extra layer I need to traverse every time I want to debug something, and bakes this extra layer in as the "wrap / extend" layer includes functionality not just string manipulation. 

This being said, I don't have the time to rewrite this the way I would like it to be, certainly with in the "pretty soon" time frames. Apropos DOE grant milestones: I counter that this code forms part of the basic processing pipeline for several operational beamlines. 

I can make no further comment at this time without causing you problems, but I know that this will come back to bite me for the reasons enumerated above.

**Comment by Anthchirp** [comment]
I suggest sticking to direct pycbf access in dxtbx and moving `dxtbx.format.cbf_wrapper` to `cctbx_project.xfel.cbf_wrapper`

**Comment by phyy-nx** [comment]
Ok, I have a rewrite coming in other pull request over the next few days.

**Pull request closed without merging**
