### PR TITLE
FormatROD set beam probe to electron for ED

### PR DESCRIPTION
**Pull request by dagewa**
The CAP format does actually have a header value to identify an ED experiment (see `b_is_microed_experiment` in sources). However we do not have a complete header reader in this format class so we cannot reliably find this value. So, use a short-wavelength heuristic to choose an electron probe.

### CODE REVIEW

**Comment by biochem-fan** [comment]
> b_is_microed_experiment in sources

Which source? The CAP format description I found is very old.

**Comment by graeme-winter** [comment]
> I was sent a zip file with source code by Mathias Meyer. If you are interested I could ask him if I can share it with you.

Technically I guess if we are using that information to implement support we kinda need some kind of license on the information / source code anyway?

**Comment by dagewa** [comment]
Potentially... there is no license file in the sources I have or in comments. I think it is a subset of a larger project. I can ask Mathias.

**Comment by dagewa** [comment]
Merging now for use, and will pick up the issue of more complete ROD support later when I hear back from Mathias

**Pull request merged**
