### PR TITLE
Calculate attenuation length per shoebox instead of per pixel

### PR DESCRIPTION
**Pull request by Anthchirp**
More details to follow

### CODE REVIEW

**Comment by jbeilstenedmands** [comment]
Current comparison of results with thaumatin dataset (from old dials tutorial):

In summary, looks like some deviation at high resolution.
Master:
```
 Summary vs resolution
 ---------------------------------------------------------------------------------------------------------
 ID | d min | # full | # part | # over | # ice | # sum | # prf | Ibg  | I/sigI | I/sigI | CC prf | RMSD XY
    |       |        |        |        |       |       |       |      |  (sum) |  (prf) |        |
 ---------------------------------------------------------------------------------------------------------
 0  | 1.17  | 358    | 12     | 0      | 0     | 251   | 182   | 0.00 | 0.40   | 0.46   | 0.00   | 0.91
 0  | 1.19  | 1134   | 30     | 0      | 0     | 1004  | 846   | 0.00 | 0.44   | 0.44   | 0.00   | 0.91
 0  | 1.21  | 2491   | 73     | 0      | 0     | 2222  | 1954  | 0.00 | 0.51   | 0.48   | 0.00   | 0.87
 0  | 1.23  | 4076   | 114    | 0      | 0     | 3698  | 3417  | 0.00 | 0.58   | 0.56   | 0.00   | 0.86
 0  | 1.26  | 5909   | 164    | 0      | 0     | 5352  | 4977  | 0.00 | 0.62   | 0.62   | 0.00   | 0.81
 0  | 1.28  | 8037   | 223    | 0      | 0     | 7185  | 6727  | 0.00 | 0.69   | 0.69   | 0.00   | 0.77
 0  | 1.31  | 10584  | 301    | 0      | 0     | 9483  | 8983  | 0.00 | 0.81   | 0.81   | 0.00   | 0.73
 0  | 1.35  | 13838  | 410    | 0      | 0     | 12463 | 11799 | 0.00 | 0.95   | 0.96   | 0.00   | 0.68
 0  | 1.38  | 18819  | 589    | 0      | 0     | 17034 | 16214 | 0.00 | 1.02   | 1.03   | 0.00   | 0.65
 0  | 1.42  | 22024  | 1654   | 0      | 0     | 20921 | 19991 | 0.00 | 1.23   | 1.26   | 0.00   | 0.63
 0  | 1.47  | 25242  | 3912   | 0      | 0     | 25393 | 24079 | 0.00 | 1.47   | 1.53   | 0.00   | 0.60
 0  | 1.52  | 26865  | 4212   | 0      | 0     | 26180 | 25212 | 0.00 | 1.77   | 1.86   | 0.00   | 0.56
 0  | 1.58  | 27109  | 4145   | 0      | 0     | 27606 | 26572 | 0.00 | 2.16   | 2.31   | 0.00   | 0.52
 0  | 1.65  | 27175  | 4233   | 0      | 0     | 26417 | 25361 | 0.00 | 2.66   | 2.85   | 0.00   | 0.48
 0  | 1.74  | 27294  | 4183   | 0      | 0     | 26967 | 25933 | 0.00 | 3.42   | 3.69   | 0.00   | 0.44
 0  | 1.85  | 27461  | 4499   | 0      | 0     | 27821 | 26684 | 0.00 | 4.72   | 5.09   | 0.00   | 0.38
 0  | 1.99  | 27512  | 4569   | 0      | 0     | 26693 | 25631 | 0.00 | 6.37   | 6.89   | 0.00   | 0.34
 0  | 2.19  | 27796  | 4431   | 0      | 0     | 28003 | 26887 | 0.00 | 8.50   | 9.30   | 0.00   | 0.33
 0  | 2.51  | 27896  | 4341   | 0      | 0     | 27398 | 26308 | 0.00 | 12.20  | 13.42  | 0.00   | 0.29
 0  | 3.16  | 28183  | 4751   | 0      | 0     | 28242 | 27094 | 0.00 | 24.23  | 26.67  | 0.00   | 0.27
 ---------------------------------------------------------------------------------------------------------
```

This branch:
```
 Summary vs resolution
 ---------------------------------------------------------------------------------------------------------
 ID | d min | # full | # part | # over | # ice | # sum | # prf | Ibg  | I/sigI | I/sigI | CC prf | RMSD XY
    |       |        |        |        |       |       |       |      |  (sum) |  (prf) |        |
 ---------------------------------------------------------------------------------------------------------
 0  | 1.17  | 358    | 12     | 0      | 0     | 262   | 182   | 0.00 | 0.43   | 0.43   | 0.00   | 1.00
 0  | 1.19  | 1134   | 30     | 0      | 0     | 1015  | 846   | 0.00 | 0.42   | 0.41   | 0.00   | 1.00
 0  | 1.21  | 2491   | 73     | 0      | 0     | 2248  | 1960  | 0.00 | 0.52   | 0.46   | 0.00   | 0.97
 0  | 1.23  | 4076   | 114    | 0      | 0     | 3721  | 3414  | 0.00 | 0.57   | 0.54   | 0.00   | 0.93
 0  | 1.26  | 5909   | 164    | 0      | 0     | 5354  | 4966  | 0.00 | 0.60   | 0.60   | 0.00   | 0.89
 0  | 1.28  | 8037   | 223    | 0      | 0     | 7204  | 6731  | 0.00 | 0.67   | 0.66   | 0.00   | 0.85
 0  | 1.31  | 10584  | 301    | 0      | 0     | 9505  | 8981  | 0.00 | 0.80   | 0.78   | 0.00   | 0.79
 0  | 1.35  | 13838  | 410    | 0      | 0     | 12488 | 11793 | 0.00 | 0.93   | 0.93   | 0.00   | 0.74
 0  | 1.38  | 18819  | 589    | 0      | 0     | 17072 | 16196 | 0.00 | 1.01   | 1.00   | 0.00   | 0.70
 0  | 1.42  | 22024  | 1654   | 0      | 0     | 20935 | 19989 | 0.00 | 1.22   | 1.22   | 0.00   | 0.67
 0  | 1.47  | 25242  | 3912   | 0      | 0     | 25424 | 24069 | 0.00 | 1.45   | 1.49   | 0.00   | 0.63
 0  | 1.52  | 26865  | 4212   | 0      | 0     | 26168 | 25196 | 0.00 | 1.76   | 1.82   | 0.00   | 0.59
 0  | 1.58  | 27109  | 4145   | 0      | 0     | 27609 | 26575 | 0.00 | 2.15   | 2.28   | 0.00   | 0.54
 0  | 1.65  | 27175  | 4233   | 0      | 0     | 26412 | 25355 | 0.00 | 2.65   | 2.81   | 0.00   | 0.50
 0  | 1.74  | 27294  | 4183   | 0      | 0     | 26961 | 25926 | 0.00 | 3.42   | 3.65   | 0.00   | 0.45
 0  | 1.85  | 27461  | 4499   | 0      | 0     | 27822 | 26684 | 0.00 | 4.72   | 5.05   | 0.00   | 0.39
 0  | 1.99  | 27512  | 4569   | 0      | 0     | 26693 | 25632 | 0.00 | 6.36   | 6.85   | 0.00   | 0.35
 0  | 2.19  | 27796  | 4431   | 0      | 0     | 28005 | 26890 | 0.00 | 8.50   | 9.27   | 0.00   | 0.34
 0  | 2.51  | 27896  | 4341   | 0      | 0     | 27412 | 26322 | 0.00 | 12.20  | 13.40  | 0.00   | 0.30
 0  | 3.16  | 28183  | 4751   | 0      | 0     | 28238 | 27090 | 0.00 | 24.24  | 26.66  | 0.00   | 0.27
 ---------------------------------------------------------------------------------------------------------
```

Merging stats after scaling:
cc_one_half
r_pim
i_over_sigma_mean

**Comment by jbeilstenedmands** [comment]
Current comparison of results with beta lactamase dataset.

Summary, again, RMSD XY values worse at high resolution, and merging stats look slightly worse for this branch. Note, runtime down from 257s to 222s in this case (my macbook, 3d_threaded, nproc2, njobs4).
Master:
```
 Summary vs resolution
 ---------------------------------------------------------------------------------------------------------
 ID | d min | # full | # part | # over | # ice | # sum | # prf | Ibg  | I/sigI | I/sigI | CC prf | RMSD XY
    |       |        |        |        |       |       |       |      |  (sum) |  (prf) |        |
 ---------------------------------------------------------------------------------------------------------
 0  | 1.21  | 379    | 3      | 0      | 0     | 196   | 106   | 0.00 | 0.28   | 0.22   | 0.00   | 0.96
 0  | 1.23  | 1330   | 10     | 0      | 0     | 956   | 780   | 0.00 | 0.25   | 0.20   | 0.00   | 0.91
 0  | 1.25  | 3231   | 22     | 0      | 0     | 2606  | 2241  | 0.00 | 0.27   | 0.23   | 0.00   | 0.87
 0  | 1.28  | 5310   | 39     | 0      | 0     | 4367  | 3990  | 0.00 | 0.32   | 0.28   | 0.00   | 0.80
 0  | 1.30  | 7647   | 51     | 0      | 0     | 6425  | 5990  | 0.00 | 0.41   | 0.36   | 0.00   | 0.74
 0  | 1.33  | 11091  | 74     | 0      | 0     | 9257  | 8736  | 0.00 | 0.46   | 0.42   | 0.00   | 0.69
 0  | 1.36  | 15188  | 469    | 0      | 0     | 13099 | 12388 | 0.00 | 0.53   | 0.48   | 0.00   | 0.64
 0  | 1.40  | 20305  | 1239   | 0      | 0     | 18311 | 17675 | 0.00 | 0.63   | 0.56   | 0.00   | 0.60
 0  | 1.43  | 22930  | 2105   | 0      | 0     | 21538 | 21194 | 0.00 | 0.73   | 0.66   | 0.00   | 0.56
 0  | 1.48  | 23438  | 2694   | 0      | 0     | 21381 | 21186 | 0.00 | 0.97   | 0.92   | 0.00   | 0.52
 0  | 1.52  | 23343  | 2654   | 0      | 0     | 21619 | 21447 | 0.00 | 1.24   | 1.18   | 0.00   | 0.48
 0  | 1.58  | 23583  | 2538   | 0      | 0     | 22461 | 22276 | 0.00 | 1.53   | 1.48   | 0.00   | 0.45
 0  | 1.64  | 23699  | 2682   | 0      | 0     | 22202 | 22014 | 0.00 | 1.88   | 1.87   | 0.00   | 0.43
 0  | 1.72  | 24022  | 2668   | 0      | 0     | 22404 | 22225 | 0.00 | 2.64   | 2.65   | 0.00   | 0.39
 0  | 1.81  | 24198  | 2810   | 0      | 0     | 22526 | 22346 | 0.00 | 3.79   | 3.90   | 0.00   | 0.37
 0  | 1.92  | 24044  | 2895   | 0      | 0     | 22698 | 22493 | 0.00 | 5.64   | 5.84   | 0.00   | 0.34
 0  | 2.07  | 24586  | 2742   | 0      | 0     | 23393 | 23190 | 0.00 | 7.91   | 8.36   | 0.00   | 0.33
 0  | 2.28  | 24634  | 2877   | 0      | 0     | 23700 | 23524 | 0.00 | 11.03  | 11.83  | 0.00   | 0.29
 0  | 2.61  | 25083  | 2752   | 0      | 0     | 23514 | 23341 | 0.00 | 17.63  | 18.82  | 0.00   | 0.26
 0  | 3.28  | 25254  | 2858   | 0      | 0     | 23950 | 23730 | 0.00 | 40.91  | 43.47  | 0.00   | 0.25
 ---------------------------------------------------------------------------------------------------------
```

This branch:
```
 Summary vs resolution
 ---------------------------------------------------------------------------------------------------------
 ID | d min | # full | # part | # over | # ice | # sum | # prf | Ibg  | I/sigI | I/sigI | CC prf | RMSD XY
    |       |        |        |        |       |       |       |      |  (sum) |  (prf) |        |
 ---------------------------------------------------------------------------------------------------------
 0  | 1.21  | 379    | 3      | 0      | 0     | 198   | 106   | 0.00 | 0.31   | 0.22   | 0.00   | 1.09
 0  | 1.23  | 1330   | 10     | 0      | 0     | 962   | 779   | 0.00 | 0.26   | 0.20   | 0.00   | 1.05
 0  | 1.25  | 3231   | 22     | 0      | 0     | 2618  | 2245  | 0.00 | 0.28   | 0.23   | 0.00   | 1.01
 0  | 1.28  | 5310   | 39     | 0      | 0     | 4382  | 3992  | 0.00 | 0.31   | 0.28   | 0.00   | 0.93
 0  | 1.30  | 7647   | 51     | 0      | 0     | 6444  | 5985  | 0.00 | 0.42   | 0.36   | 0.00   | 0.88
 0  | 1.33  | 11091  | 74     | 0      | 0     | 9277  | 8733  | 0.00 | 0.47   | 0.41   | 0.00   | 0.82
 0  | 1.36  | 15188  | 469    | 0      | 0     | 13140 | 12405 | 0.00 | 0.54   | 0.47   | 0.00   | 0.78
 0  | 1.40  | 20305  | 1239   | 0      | 0     | 18366 | 17685 | 0.00 | 0.63   | 0.55   | 0.00   | 0.73
 0  | 1.43  | 22930  | 2105   | 0      | 0     | 21544 | 21194 | 0.00 | 0.73   | 0.65   | 0.00   | 0.69
 0  | 1.48  | 23438  | 2694   | 0      | 0     | 21373 | 21176 | 0.00 | 0.98   | 0.90   | 0.00   | 0.65
 0  | 1.52  | 23343  | 2654   | 0      | 0     | 21636 | 21465 | 0.00 | 1.25   | 1.17   | 0.00   | 0.61
 0  | 1.58  | 23583  | 2538   | 0      | 0     | 22464 | 22280 | 0.00 | 1.54   | 1.46   | 0.00   | 0.56
 0  | 1.64  | 23699  | 2682   | 0      | 0     | 22182 | 21993 | 0.00 | 1.88   | 1.83   | 0.00   | 0.52
 0  | 1.72  | 24022  | 2668   | 0      | 0     | 22412 | 22233 | 0.00 | 2.64   | 2.61   | 0.00   | 0.47
 0  | 1.81  | 24198  | 2810   | 0      | 0     | 22542 | 22361 | 0.00 | 3.80   | 3.86   | 0.00   | 0.43
 0  | 1.92  | 24044  | 2895   | 0      | 0     | 22688 | 22485 | 0.00 | 5.65   | 5.79   | 0.00   | 0.39
 0  | 2.07  | 24586  | 2742   | 0      | 0     | 23384 | 23182 | 0.00 | 7.92   | 8.30   | 0.00   | 0.36
 0  | 2.28  | 24634  | 2877   | 0      | 0     | 23719 | 23542 | 0.00 | 11.03  | 11.77  | 0.00   | 0.30
 0  | 2.61  | 25083  | 2752   | 0      | 0     | 23529 | 23356 | 0.00 | 17.64  | 18.77  | 0.00   | 0.27
 0  | 3.28  | 25254  | 2858   | 0      | 0     | 23969 | 23749 | 0.00 | 40.90  | 43.44  | 0.00   | 0.25
 ---------------------------------------------------------------------------------------------------------
```

Merging statistics:
cc_one_half
r_pim
i_over_sigma_mean

**Comment by jbeilstenedmands** [comment]
Two warnings raised by clang in this branch:
```
/dials/modules/dxtbx/model/pixel_to_millimeter.h:143:12: warning: 
      'dxtbx::model::ParallaxCorrectedPxMmStrategy::attenuation_length' hides overloaded virtual function [-Woverloaded-virtual]
    double attenuation_length(const PanelData &panel, vec2<double> xy) {
           ^
/dials/modules/dxtbx/model/pixel_to_millimeter.h:44:20: note: hidden overloaded virtual function
      'dxtbx::model::PxMmStrategy::attenuation_length' declared here: different qualifiers (const vs none)
    virtual double attenuation_length(const PanelData &panel, vec2<double> xy) const {
```

```
/dials/modules/boost/boost/python/detail/destroy.hpp:20:9: warning: destructor called on non-final
      'dxtbx::masking::GoniometerShadowMasker' that has virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
        p->~T();
        ^
/dials/modules/boost/boost/python/detail/destroy.hpp:52:8: note: in instantiation of function template specialization
      'boost::python::detail::value_destroyer<false>::execute<dxtbx::masking::GoniometerShadowMasker>' requested here
    >::execute((const volatile T*)p);
       ^
/dials/modules/boost/boost/python/detail/destroy.hpp:58:5: note: in instantiation of function template specialization
      'boost::python::detail::destroy_referent_impl<const dxtbx::masking::GoniometerShadowMasker>' requested here
    destroy_referent_impl(p, (T(*)())0);
    ^
/dials/modules/boost/boost/python/converter/rvalue_from_python_data.hpp:135:25: note: in instantiation of function template
      specialization 'boost::python::detail::destroy_referent<const dxtbx::masking::GoniometerShadowMasker &>' requested here
        python::detail::destroy_referent<ref_type>(this->storage.bytes);
                        ^
/dials/modules/boost/boost/python/converter/arg_from_python.hpp:107:8: note: in instantiation of member function
      'boost::python::converter::rvalue_from_python_data<const dxtbx::masking::GoniometerShadowMasker &>::~rvalue_from_python_data'
      requested here
struct arg_rvalue_from_python
       ^
/dials/modules/boost/boost/python/object/py_function.hpp:38:16: note: in instantiation of member function
      'boost::python::detail::caller_arity<1>::impl<boost::python::tuple (*)(const dxtbx::masking::GoniometerShadowMasker &),
      boost::python::default_call_policies, boost::mpl::vector2<boost::python::tuple, const dxtbx::masking::GoniometerShadowMasker &>
      >::operator()' requested here
        return m_caller(args, kw);
               ^
/dials/modules/boost/boost/python/object/py_function.hpp:32:5: note: (skipping 4 contexts in backtrace; use
      -ftemplate-backtrace-limit=0 to see all)
    caller_py_function_impl(Caller const& caller)
    ^
/dials/modules/boost/boost/python/class.hpp:497:13: note: in instantiation of function template specialization
      'boost::python::make_function<boost::python::tuple (*)(const dxtbx::masking::GoniometerShadowMasker &),
      boost::python::default_call_policies, boost::python::detail::keywords<0>, boost::mpl::vector2<boost::python::tuple, const
      dxtbx::masking::GoniometerShadowMasker &> >' requested here
          , make_function(
            ^
/dials/modules/boost/boost/python/class.hpp:235:15: note: in instantiation of function template specialization
      'boost::python::class_<dxtbx::masking::GoniometerShadowMasker, boost::python::detail::not_specified,
      boost::python::detail::not_specified, boost::python::detail::not_specified>::def_impl<dxtbx::masking::GoniometerShadowMasker,
      boost::python::tuple (*)(const dxtbx::masking::GoniometerShadowMasker &), boost::python::detail::def_helper<const char *,
      boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> >' requested here
        this->def_impl(
              ^
/dials/modules/boost/boost/python/object/pickle_support.hpp:62:10: note: in instantiation of function template specialization
      'boost::python::class_<dxtbx::masking::GoniometerShadowMasker, boost::python::detail::not_specified,
      boost::python::detail::not_specified, boost::python::detail::not_specified>::def<boost::python::tuple (*)(const
      dxtbx::masking::GoniometerShadowMasker &)>' requested here
      cl.def("__getinitargs__", getinitargs_fn);
         ^
/dials/modules/boost/boost/python/class.hpp:345:55: note: in instantiation of function template specialization
      'boost::python::detail::pickle_suite_registration::register_<boost::python::class_<dxtbx::masking::GoniometerShadowMasker,
      boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>, const
      dxtbx::masking::GoniometerShadowMasker &>' requested here
      detail::pickle_suite_finalize<PickleSuiteType>::register_(
                                                      ^
/dials/modules/dxtbx/masking/boost_python/ext.cc:89:8: note: in instantiation of function template specialization
      'boost::python::class_<dxtbx::masking::GoniometerShadowMasker, boost::python::detail::not_specified,
      boost::python::detail::not_specified,
      boost::python::detail::not_specified>::def_pickle<dxtbx::masking::boost_python::GoniometerShadowMaskerPickleSuite>' requested here
      .def_pickle(GoniometerShadowMaskerPickleSuite());
       ^
/dials/modules/boost/boost/python/detail/destroy.hpp:20:13: note: qualify call to silence this warning
        p->~T();
            ^
            dxtbx::masking::GoniometerShadowMasker::
```

**Comment by biochem-fan** [comment]
When the difference is small, looking at peak heights in anomalous difference maps sometimes help. CC1/2 measures only internal consistency, not accuracy. I/sig can be biased by sigma estimates.

**Comment by jbeilstenedmands** [comment]
After adding const qualifier, results are almost indistinguishable : in integrate summary, one more reflection processed and changes by 0.01 in some of the I/sigI column values.
Merging stats now identical:
cc_one_half

**Comment by dagewa** [comment]
The branch should now be working as intended. Here is a scatterplot of the difference in the attenuation length for each pixel compared to the cached value for the shoebox, as a function of radial distance from the centre of the detector:
foo
The approximation looks reasonable even at high angle, and there is no systematic trend - just greater scatter for higher angle spots.

**Pull request merged**
