### PR TITLE
Cleanup command line

### PR DESCRIPTION
**Pull request by rjgildea**
Remove several command line programs that are either broken, untested, or duplicate functionality of various dials command line programs:
- dxtbx.print_sequence
- dxtbx.print_sequence_check
- dxtbx.serialize
- dxtbx.print_beam_centre
- dxtbx.to_xds
- dxtbx.to_ewald_sphere
- dxtbx.import_datablock
- dxtbx.export_bitmaps

### CODE REVIEW

**Comment by phyy-nx** [comment]
@rjgildea we use dxtbx.print_header all the time.  Please don't remove it?

**Comment by rjgildea** [comment]
> @rjgildea we use dxtbx.print_header all the time. Please don't remove it?

But it pretty much does exactly what dials.show does - why can't you use that instead? Plus dxtbx.print_header isn't tested, so there isn't any guarantee that it will actually work.

**Comment by nksauter** [comment]
Presumably dxtbx.print_header will work in a cctbx-only installation
independent of whether the user installs dials?  This is reason enough to
preserve it.
Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by graeme-winter** [comment]
I thought the cctbx only installers don’t include dxtbx because of the HDF5 dependency? This was mentioned on cctbx bb earlier

**Comment by phyy-nx** [comment]
(Agree about the dxtbx-only installation issue)

Honestly I didn't know dials.show could work on raw image files.
Importantly though, dxtbx.print_header includes "Total Counts: 930610762"
(example from a cbf).  This is nice because it proves the data can be read
without using the image viewer.  Useful for fast development (like at a
beamline).

Adding a test would be good.

**Comment by graeme-winter** [comment]
Same token, adding ability to sum a frame to dials show would meet your brief?

Your use case is a valid one, which deserves a supported tool. Point well made, thank you.

**Comment by Anthchirp** [comment]
cctbx default installation dxtbx, but without HDF5 and without undeclared dependencies such as xfel.

You get a half-install.

**Comment by phyy-nx** [comment]
No, I think having a quick way to exercise dxtbx without having dials
installed is valuable.  While the current cctbx conda package being worked
on doesn't include dxtbx, my understanding is that's temporary.  The cctbx
builder in bootstrap includes dxtbx.  It's the cctbx-lite builder which
does not.

**Comment by Anthchirp** [comment]
Eventually there will be one (more realistically: multiple) dxtbx conda packages, but that is not on the horizon yet. There are many open packaging questions that need to be resolved first.

I don't see the harm of keeping the command around. dxtbx does not suffer from overcrowding.

On-board with removing the broken ones.

**Comment by Anthchirp** [comment]
fwiw the canonical way to exercise dxtbx without dials installed is
`libtbx.pip install dials_data; pytest --regression $path_to_dxtbx`

**Comment by dagewa** [comment]
I also feel that as dxtbx is a library to read image headers and image data, and create experiment models from them, it deserves to have a tool that shows what it is doing.

@phyy-nx you might like to look at, for example, `dials.show image_statistics.show_raw=True`, which gives a five number summary (more useful to my eyes than a total count)

**Comment by rjgildea** [comment]
As @dagewa says, dials.show supports showing image statistics with the `image_statistics.show_raw=True` option. It would be relatively trivial to extend this to also show the total counts, and then dials.show functionality would be entirely a superset of dxtbx.print_header.

**Comment by phyy-nx** [comment]
image_statistics.show_raw=True does seem more useful than total counts.

**Comment by dagewa** [comment]
You can also show_corrected=True if you like ;-)

**Comment by asmit3** [comment]
If print_header is removed, is there any other command line tool within dxtbx that one can use to check if an image file is readable by dxtbx/if a format class is working ? Since dxtbx is a library that is supposed to read in image files and represent them in a standard format, such a tool should be self contained and independent of downstream packages that do data processing/visualization.

**Comment by Anthchirp** [comment]
`dxtbx.show_matching_formats` will tell you what format classes are tested against the file and which ones match. `dxtbx.show_registry` shows only the hierarchy of matching format classes.

**Comment by asmit3** [comment]
@Anthchirp 
a) The output from show_matching_formats is hard to read
b) It does not print out any of the information **after** assembling a dxtbx experimental model. For example wavelength and gain could be read in from the image file. The most important one of course I have found is the fast axis, slow axis and detector origin values that we absolutely need to get right in the format class before using downstream data processing packages. Hence this kind of a tool needs to be kept in dxtbx.

**Comment by graeme-winter** [comment]
I'm pretty happy that `print_header` remain - it *is* a tool I use myself and even if `dials.show` supersedes it, there's no argument to remove it as it works and is doing no harm. 

Adding a test would be appropriate.

**Comment by asmit3** [comment]
@graeme-winter thanks for keeping the tool and adding a test. Appreciate it.

**Pull request merged**
