### PR TITLE
Retire format readers

### PR DESCRIPTION
**Pull request by Anthchirp**
as far as I can tell this is unused code and can safely be retired.
dxtbx, dials, and iotbx tests still build and pass.

### CODE REVIEW

**Comment by graeme-winter** [comment]
ISTR idea behind these was to allow C++ readers everywhere - which should probably be a goal, still? Maybe? #discuss

**Comment by phyy-nx** [comment]
Hi, help me understand?  I'm surprised these files are unused.  Are the cbf/smv/hdf5/tiff_reader.h not used by dxtbx?  Is that because iotbx functionality is being used instead?  I think these c++ implementations of file readers look useful.

**Comment by Anthchirp** [comment]
Not used anywhere in the packages mentioned above, neither python nor C++.

As to whether the code is *useful* I cannot say. All I did was grepping the source for "Reader" followed by some reference counting.

**Comment by phyy-nx** [comment]
@jmp1985?

**Comment by jmp1985** [comment]
These classes were originally written so that files could be read in C++ without going into python. Tbh I can't remember why I didn't actually end up using them, possibly running out of time and having to do something else.

**Comment by Anthchirp** [comment]
Files appear to mostly be from August-November 2017. The tests were touched in May 2018 when I converted them to pytest.

I'm not invested either way as to what we do with this.

**Comment by Anthchirp** [comment]
GW suggested we create a branch https://github.com/cctbx/dxtbx/tree/dxtbx-with-c%2B%2B-image-readers and merge

**Pull request merged**
