### PR TITLE
Python 3: lib2to3.fixes.fix_map

### PR DESCRIPTION
**Pull request by Anthchirp**
This pull request is based on the lib2to3.fixes.fix_map fixer. In Python 3 `map()` returns a map object, which basically are iterators. The automatic fixer wraps every `map()` call in `list()` to restore previous behaviour.

### CODE REVIEW

**Comment by Anthchirp** [comment]
The refactoring of the SMV code raised a question. As the diff for commit https://github.com/cctbx/dxtbx/pull/43/commits/d6b8cd141dc9fe9f057cb1352205f5609ec7464c shows there are a few SMV format classes that make use of a `SPATIAL_DISTORTION_VECTORS` header. Two classes (RigakuA200 and RigakuSaturn) use these as float values, others (RigakuEiger, RigakuPilatus) cast them to ints. Is that on purpose or may that be a bug? Paging @dagewa as the author.

**Comment by Anthchirp** [comment]
This is good to go, apart from the open SMV question above. (The current `int`-casting behaviour is kept, so the SMV question does not technically block the pull request)

**Comment by Anthchirp** [comment]
dxtbx and dials tests pass. No dxtbx python3 regressions.

**Comment by dagewa** [comment]
> The refactoring of the SMV code raised a question. As the diff for commit [d6b8cd1](https://github.com/cctbx/dxtbx/commit/d6b8cd141dc9fe9f057cb1352205f5609ec7464c) shows there are a few SMV format classes that make use of a `SPATIAL_DISTORTION_VECTORS` header. Two classes (RigakuA200 and RigakuSaturn) use these as float values, others (RigakuEiger, RigakuPilatus) cast them to ints. Is that on purpose or may that be a bug? Paging @dagewa as the author.

Not sure I authored those bits, but the [Rigaku header documentation](https://www.rigaku.com/downloads/software/free/dTREK%20Image%20Format%20v1.1.pdf) suggests these should be floats.

**Comment by Anthchirp** [comment]
Sorry, misread the blame log. Lines were written by @graeme-winter.
I'll assume this is a bug and will remove the `int` cast

**Pull request merged**
