### PR TITLE
Negativity is OK

### PR DESCRIPTION
**Pull request by graeme-winter**
Allow rotation angles to be < 0 i.e. crystals rocking back and forth in the beam for efficiency. Addresses #8

### CODE REVIEW

**Comment by graeme-winter** [comment]
I know the tests are now failing, need to add some fixes - I am also not sure if my implementation of range checks is 100% appropriate...

**Comment by graeme-winter** [comment]
OK, making some headway but I note

```
RMSDs by experiment:
+-------+--------+----------+----------+------------+
|   Exp |   Nref |   RMSD_X |   RMSD_Y |     RMSD_Z |
|    id |        |     (px) |     (px) |   (images) |
|-------+--------+----------+----------+------------|
|     0 |     63 |  1.8531  |  1.7814  |   10.511   |
|     1 |    158 |  0.24348 |  0.2089  |    0.45605 |
|     2 |     61 |  1.2171  |  0.96518 |    7.6812  |
|     3 |    161 |  0.24365 |  0.21047 |    0.4621  |
|     4 |     58 |  1.9206  |  1.7831  |   10.913   |
|     5 |    161 |  0.24151 |  0.21158 |    0.4643  |
|     6 |     58 |  1.9876  |  1.7574  |   10.976   |
|     7 |    163 |  0.24846 |  0.21523 |    0.48239 |
|     8 |     68 |  2.9951  |  1.7253  |   10.281   |
|     9 |    163 |  0.2421  |  0.21458 |    0.46903 |
|    10 |     59 |  2.2079  |  1.6889  |   10.903   |
|    11 |    170 |  0.24719 |  0.2096  |    0.46476 |
|    12 |     59 |  2.5397  |  1.7366  |   10.123   |
|    13 |    163 |  0.24582 |  0.20765 |    0.4522  |
|    14 |     55 |  3.0492  |  2.3804  |   11.433   |
|    15 |    158 |  0.2443  |  0.21919 |    0.45156 |
|    16 |    155 |  0.25644 |  0.21061 |    0.43657 |
|    17 |     57 |  1.257   |  1.038   |    7.0625  |
|    18 |    150 |  0.25285 |  0.21049 |    0.43558 |
|    19 |     59 |  5.5194  |  3.7083  |   16.412   |
|    20 |    159 |  0.26409 |  0.22607 |    0.48125 |
|    21 |     56 |  1.1141  |  0.97138 |    6.9746  |
|    22 |    157 |  0.2401  |  0.22664 |    0.44579 |
|    23 |     58 |  3.2405  |  3.9168  |   13.398   |
|    24 |    162 |  0.2625  |  0.23196 |    0.47992 |
|    25 |     57 |  2.7778  |  1.9703  |   12.458   |
|    26 |    159 |  0.24655 |  0.23289 |    0.48205 |
|    27 |     54 |  1.2691  |  1.0379  |    7.3207  |
|    28 |    160 |  0.24309 |  0.22314 |    0.48673 |
|    29 |     60 |  4.4311  |  2.8821  |   12.48    |
|    30 |    159 |  0.24442 |  0.21827 |    0.47197 |
|    31 |     61 |  4.6473  |  3.2832  |   13.094   |
|    32 |    161 |  0.23217 |  0.22445 |    0.46301 |
|    33 |     60 |  2.1844  |  2.5252  |   10.374   |
|    34 |    156 |  0.24484 |  0.22297 |    0.46679 |
|    35 |     56 |  4.1575  |  2.5257  |   12.867   |
|    36 |    157 |  0.24149 |  0.22287 |    0.48058 |
|    37 |     52 |  1.8935  |  1.7647  |    9.543   |
|    38 |    159 |  0.25266 |  0.22815 |    0.4932  |
|    39 |     77 |  3.2387  |  2.432   |   11.455   |
|    40 |    171 |  0.22129 |  0.21806 |    0.45772 |
|    41 |     59 |  3.5359  |  1.9308  |   12.289   |
|    42 |    173 |  0.22982 |  0.2261  |    0.46505 |
|    43 |     64 |  9.3148  |  5.1881  |   22.002   |
|    44 |    173 |  0.22575 |  0.22306 |    0.47167 |
|    45 |    174 |  0.21977 |  0.20801 |    0.49399 |
|    46 |     66 |  1.3626  |  2.0823  |    8.4106  |
|    47 |    178 |  0.22852 |  0.21493 |    0.44264 |
|    48 |     52 |  3.2143  |  1.36    |   10.65    |
|    49 |    170 |  0.22087 |  0.20893 |    0.44584 |
|    50 |     59 |  1.0922  |  1.6065  |    6.8502  |
|    51 |    166 |  0.217   |  0.20394 |    0.46364 |
|    52 |     52 |  2.9159  |  1.7797  |    9.5362  |
|    53 |    163 |  0.21611 |  0.19682 |    0.48858 |
|    54 |     58 |  1.4748  |  2.1621  |    8.4347  |
|    55 |    162 |  0.21806 |  0.22072 |    0.445   |
|    56 |    157 |  0.22594 |  0.20796 |    0.45759 |
|    57 |     65 |  2.9086  |  1.882   |   11       |
|    58 |    165 |  0.21418 |  0.23307 |    0.47467 |
|    59 |     58 |  2.6524  |  1.8777  |   10.924   |
|    60 |    171 |  0.22044 |  0.24705 |    0.47103 |
|    61 |     66 |  4.6978  |  3.7421  |   15.977   |
|    62 |    167 |  0.21505 |  0.23001 |    0.49055 |
|    63 |     57 |  9.8919  |  5.1881  |   21.858   |
|    64 |    171 |  0.2195  |  0.23262 |    0.49127 |
|    65 |     61 |  5.0362  |  3.7304  |   13.727   |
|    66 |    170 |  0.22605 |  0.21809 |    0.48776 |
|    67 |     61 |  4.1438  |  2.0564  |   13.664   |
|    68 |    169 |  0.21948 |  0.22723 |    0.46967 |
|    69 |     61 |  3.8856  |  2.0136  |   12.696   |
|    70 |    166 |  0.21941 |  0.22999 |    0.48493 |
|    71 |     56 |  3.3654  |  2.3387  |   12.183   |
|    72 |    160 |  0.21999 |  0.22507 |    0.46321 |
|    73 |     61 |  3.9333  |  1.97    |   12.444   |
|    74 |    157 |  0.21452 |  0.22793 |    0.46495 |
|    75 |     53 |  1.0753  |  2.2374  |    7.0607  |
|    76 |    153 |  0.21965 |  0.22237 |    0.46659 |
|    77 |     68 |  2.7407  |  2.2165  |   14.373   |
|    78 |    172 |  0.23193 |  0.21269 |    0.45298 |
|    79 |     66 |  3.6329  |  2.896   |   15.7     |
|    80 |    171 |  0.23343 |  0.2117  |    0.45152 |
|    81 |     57 |  1.7252  |  1.3821  |    8.1661  |
|    82 |    170 |  0.23427 |  0.21513 |    0.43396 |
|    83 |     67 |  5.7208  |  3.8996  |   12.534   |
|    84 |    176 |  0.22969 |  0.21307 |    0.48725 |
|    85 |     63 |  1.4454  |  2.1612  |    7.5644  |
|    86 |    179 |  0.23675 |  0.20925 |    0.46351 |
|    87 |     59 |  1.73    |  1.7419  |    9.9468  |
|    88 |    174 |  0.23158 |  0.20898 |    0.45434 |
|    89 |     60 |  1.8393  |  1.8091  |    9.9799  |
|    90 |    167 |  0.23336 |  0.20619 |    0.44187 |
|    91 |     72 |  2.6462  |  3.3089  |   10.709   |
|    92 |    165 |  0.23394 |  0.20603 |    0.43454 |
|    93 |     62 |  2.1917  |  2.5322  |    9.5858  |
|    94 |    163 |  0.23306 |  0.20786 |    0.4548  |
|    95 |     63 |  1.4355  |  1.9824  |    7.6993  |
|    96 |    161 |  0.23479 |  0.20727 |    0.44407 |
+-------+--------+----------+----------+------------+
```

We have a very clear pattern here so I think there is something wrong with the refinement code as well.

**Comment by graeme-winter** [comment]
From deep in the onion mine I suspect that this will be far more invasive than it seems right now, will explore a plan B

**Comment by ndevenish** [comment]
To be clear, you are asking me to merge:
image
?

**Comment by graeme-winter** [comment]
History rewritten

**Pull request merged**
