### PR TITLE
Make FormatHDF5SaclaMPCCD lazy

### PR DESCRIPTION
**Pull request by dwpaley**
- Add FormatMultiImageLazy as a mixin

- ~Bugfix in FormatMultiImage: If we're creating an ImageSetLazy, we still
  need to get the static mask from the format class and add it to the
  imageset.~ [Applied separately in #268 - ND]

Co-authored-by: Aaron Brewster <asbrewster@lbl.gov>

### CODE REVIEW

**Comment by phyy-nx** [comment]
@biochem-fan do you have time to review this since it touches the SACLA format class?

**Comment by biochem-fan** [comment]
This looks fine to me but I don't have time to test this by re-processing something at the moment. Can you process lysozyme or something and make sure?

**Comment by ndevenish** [comment]
This looks fine, as long as you are happy this doesn't break biochem-fan's cases.

Probably needs a `newsfragments/227.bugfix` for the Lazy masking fix.

**Comment by ndevenish** [comment]
Okay, so a couple of extra points:
- I've raised the scope of `_add_static_mask_to_iset` - since it doesn't capture variables, I think it reads clearer being moved - with it inline I have to study and understand the entire function when trying to read `get_imageset`, to check that it isn't relying on anything in surrounding scopes.
- I've merged the changes from master so that other fixes are in, and with these changes (I tested with and without the above move) the test `test_single_file_indices` introduced in https://github.com/cctbx/dxtbx/commit/cb6e61bc2930f53540920b1ce95c7dc44b3306ac fails on
  ```
  - >           assert obj.call_count == expected_call_count
  E           AssertionError: assert 2 == 4
  ```
  I presume that the expected call count is supposed to change, but given that you introduced the test and this change probably you are in the best place to judge that.

**Comment by ndevenish** [comment]
And, because I want to get it in for DIALS 3.3, I've separated the bugfix parts into https://github.com/cctbx/dxtbx/pull/268 (which will be merged once the CI tests pass).

**Comment by phyy-nx** [comment]
I've fixed the test_single_file_indices problem in fa895eb and fa895eb by explicitly testing with or without the lazy parameter.  I've also ran @biochem-fan's requested test.  I've ran dials.import on [SACLA-MPCCD-Phase3-21528-5images.h5](https://github.com/dials/data-files/blob/master/image_examples/SACLA-MPCCD-Phase3-21528-5images.h5), which has a static mask, then I've ran dials.find spots with an without a custom mask.  The static mask and the custom mask are both used.  I then disabled the static mask manually to double check I got different results.  So I think we are good to go on this.

**Comment by ndevenish** [comment]
I'm a little concerned with the sprinkling of `iset.reader().nullify_format_instance()`(#245) everywhere and that it's compensating for something broken in the implementation of the `Format*Lazy` classes. I'd feel happier if we understood where this problem was coming from.

That said, It only seems to be in tests that use `FormatHDF5SaclaMPCCD` directly and I don't know if the stuff tested in e.g. `test_multi_panel_gain_map` is used by anything outside of this format class.

If it's just for these cases, then I guess as you are happy it's fine.

**Comment by phyy-nx** [comment]
At the moment it's just for those cases and practically speaking only matters in tests like these where the same file is loaded in different ways.  It's documented in #245 (and I don't have an idea how to fix it at present).

**Pull request merged**
