### PR TITLE
FullCBFWriter: repair the panel shuffling bug (#745)

### PR DESCRIPTION
**Pull request by biochem-fan**
This fixes the bug reported in https://github.com/cctbx/dxtbx/issues/745, which also contains test datasets.

### CODE REVIEW

**Comment by phyy-nx** [comment]
Oh I see, great find.  Ok, I'd like to test this a bit on my side.   Will be quick about it.

**Review by phyy-nx — APPROVED** [review]
Looks good.  I tested it on the [JF16M Zenodo deposition](https://zenodo.org/records/3834335) using dxtbx.image_average and got the same result (binary identical using diff).  Thanks!

**Comment by biochem-fan** [comment]
@phyy-nx Thank you very much for your review.

**Comment by ndevenish** [comment]
I squashed the commit down on main :)

**Pull request merged**
