### PR TITLE
Python 3: libfuturize.fixes.fix_xrange_with_import

### PR DESCRIPTION
**Pull request by Anthchirp**
This pull request is based on the `Libfuturize.fixes.fix_xrange_with_import` fixer. In Python 3 `xrange()` is gone and `range` returns a `range` object, which basically is an iterator. The automatic fixer wraps every `range()` call in `list()` to restore previous behaviour and adds a `from builtins import range` line to each file using `range()` to change its behaviour to that in Python 3.

### CODE REVIEW

**Comment by Anthchirp** [comment]
dxtbx and dials tests pass, no dxtbx 3 regressions.
Remaining flake8 warnings overlap with #47 / #49 or are more involved.

**Comment by graeme-winter** [comment]
@Anthchirp if memory serves, when @ndevenish and I looked into things like this we found `six.range` a quicker replacement as `builtins.range` (as a full back-port) did more. However if the issues here are not time-critical (as we found for cctbx) then `builtins.range` is cleaner.

**Comment by Anthchirp** [comment]
timings for a single run of dxtbx regression tests with cleared caches:

. | master | pull request
--- | ---------- | -------------
pytest | 44.38s | 44.30s
time real | 0m46.779s | 0m46.569s
time user | 3m59.675s | 3m58.610s
time sys | 0m34.084s | 0m34.278s

timings for a single run of the dials regression tests with cleared caches:

. | master | pull request
--- | ---------- | -------------
pytest | 339.52s | 330.85s
time real | 5m41.858s | 5m33.716s
time user | 37m8.106s | 37m18.761s
time sys | 2m35.755s | 2m34.278s

**Comment by ndevenish** [comment]
> @Anthchirp if memory serves, when @ndevenish and I looked into things like this we found `six.range` a quicker replacement as `builtins.range` (as a full back-port) did more. However if the issues here are not time-critical (as we found for cctbx) then `builtins.range` is cleaner.

To add to this - `six.moves.range` is literally `xrange` on python 2, whereas `builtins.range` is a special python-implementation range object that implements the new behaviour (__contains__, slicing, equality). This _was_ causing slowdown in the cctbx python 2 tests, but this slowdown was minor and will go away when we switch to python 3, so we don't really need to worry about it.

**Pull request merged**
