### PR TITLE
Update Azure builds

### PR DESCRIPTION
**Pull request by Anthchirp**
* Remove build caches, because they're not trustworthy anyway (cf. #300)
* Base all builds on pre-built conda-forge cctbx packages (fixed version)
* Replace miniconda with micromamba
* Cut build times from around 35-45 to below 15 minutes

Interestingly, this breaks some MacOS tests in `dxtbx_ext`:
```
_______________________________ test_dlsnxs2cbf ________________________________
[gw2] darwin -- Python 3.6.13 /Users/runner/work/1/build/../conda_base/bin/python3.6

dials_data = <DataFetcher: /Users/runner/work/1/data>
tmp_path = PosixPath('/Users/runner/work/1/tests/popen-gw2/test_dlsnxs2cbf0')

    def test_dlsnxs2cbf(dials_data, tmp_path):
        screen = dials_data("thaumatin_eiger_screen")
        master = screen.join("Therm_6_1_master.h5")
        result = procrunner.run(
            ["dxtbx.dlsnxs2cbf", master, "junk_%04d.cbf"], working_directory=tmp_path
        )
>       assert not result.returncode and not result.stderr
E       AssertionError: assert (not -6)
E        +  where -6 = ReturnObject(args=('dxtbx.dlsnxs2cbf', '/Users/runner/work/1/data/thaumatin_eiger_screen/Therm_6_1_master.h5', 'junk_%... 0x80000000)), function cbf_compress, file /Users/runner/work/1/modules/dxtbx/boost_python/compression.cc, line 91.\n').returncode

/Users/runner/work/1/modules/dxtbx/tests/command_line/test_dlsnxs2cbf.py:16: AssertionError
----------------------------- Captured stdout call -----------------------------
Assertion failed: ((-0x7fffffff <= delta) && (delta < 0x80000000)), function cbf_compress, file /Users/runner/work/1/modules/dxtbx/boost_python/compression.cc, line 91.
```
and
```
worker 'gw0' crashed while running 'tests/test_compression.py::test_compress_decompress'
```

### CODE REVIEW

**Comment by Anthchirp** [comment]
Instructions to set up a (MacOS) dxtbx+prebuilt cctbx environment:
```bash
$ mkdir dxbtx-without-cctbx && cd dxbtx-without-cctbx
$ git clone https://github.com/dials/annlib.git modules/annlib
$ git clone https://github.com/dials/annlib_adaptbx.git modules/annlib_adaptbx
$ git clone -b azure https://github.com/cctbx/dxtbx.git modules/dxtbx
$ python3 modules/dxtbx/.azure-pipelines/bootstrap.py update base
$ . conda_base/bin/activate
$ mkdir build && cd build
$ libtbx.configure dxtbx cbflib_adaptbx && make
$ cd ..
```
And then to run tests in a new terminal:
```bash
$ . conda_base/bin/activate
$ . build/setpaths.sh
$ cd modules/dxtbx
$ pytest -v -ra -n auto --regression
```

**Comment by graeme-winter** [comment]
Verified 2 x test failures on 

```
Darwin Grey-Area.home 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```

**Comment by graeme-winter** [comment]
Datum:

test passes with this change

```
diff --git a/tests/test_compression.py b/tests/test_compression.py
index e84a1a4..dbcf9b6 100644
--- a/tests/test_compression.py
+++ b/tests/test_compression.py
@@ -7,7 +7,7 @@ def test_compress_decompress():
     x, y = 10, 10
 
     data = flex.int(x * y, 1)
-    data[10] = 44369
+    data[10] = 12345 #44369
     data[11] = 214
     compressed = compress(data)
     uncompressed = uncompress(compressed, x, y)
``` 

-> it is to do with the shift between pixel j, j+1 being > 0x7fff

**Comment by graeme-winter** [comment]
In debugger:

```
Assertion failed: ((-0x7fffffff <= delta) && (delta < 0x80000000)), function cbf_compress, file /Users/graeme/debug/dxtbx-351/dxbtx-without-cctbx/modules/dxtbx/boost_python/compression.cc, line 91.
Process 37384 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #4: 0x00000001043a82fa dxtbx_ext.so`dxtbx::boost_python::cbf_compress(int const*, unsigned long const&) + 1914
dxtbx_ext.so`dxtbx::boost_python::cbf_compress:
->  0x1043a82fa <+1914>: jmp    0x1043a835d               ; <+2013>
    0x1043a82fc <+1916>: movq   -0x30(%rbp), %rdi
    0x1043a8300 <+1920>: callq  0x1043a888e               ; symbol stub for: std::__1::__vector_base_common<true>::__throw_length_error() const
    0x1043a8305 <+1925>: jmp    0x1043a835d               ; <+2013>
Target 0: (python3) stopped.
```

_obviously_ we know that the `delta` here must be between these two extrema -> some memory error -> will continue

**Comment by Anthchirp** [comment]
Fix correctly fixed the builds. This is now ready for review.

**Pull request merged**
