### PR TITLE
Correct update warning message

### PR DESCRIPTION
**Pull request by benjaminhwilliams**
Correct a warning message about using an outdated version of the `hdf5-external-filter-plugins` package.
The suggested command to fix the warning is now given as `conda update hdf5-external-filter-plugins`.

s/install/update/

### CODE REVIEW

**Comment by ndevenish** [comment]
This looks probably fine.

I remain mildly concerned about conda's tendency to go "ahah! you want to update one package? Then all bets are off for constraints!" and try to update every package in the thing (running this command updates 35 packages, and downgrades or removes 8, just to nudge a single build number), but as a transition for dev builds this is probably fine, especially as the old command didn't seem to work.

**Comment by benjaminhwilliams** [comment]
OK, equally happy to merge or close.  I don't have enough Conda nous to have anticipated the unintended consequences...

**Comment by Anthchirp** [comment]
`conda install "hdf5-external-filter-plugins==0.1.0[build_number='>=5']"` is a more defensive alternative.

I would also suggest that we remove the warning and backwards compatibility at some point.
The change (https://github.com/cctbx/dxtbx/pull/258) went in in mid-November.

**Comment by Anthchirp** [comment]
or just leave it here, but take it out of dx2

**Review by Anthchirp — APPROVED** [review]

**Comment by ndevenish** [comment]
So, in view of at least one person still having this be broken, I think it's worth changing the deprecation schedule to remove at/before 3.4, [currently](https://github.com/dials/dials/wiki/Version-Release-History) slated for 2021-03-15.

I don't think there's any real harm in leaving this in a bit longer.

**Pull request merged**
