### PR TITLE
  Ensure HDF5 has plugin paths configured before usage

### PR DESCRIPTION
**Pull request by ndevenish**
#265 restored the autoconfiguration-magic of making sure HDF5 plugins were found when working in a moved conda-environment (e.g. by the DIALS installer). However, this reintroduced the problem discussed in cctbx/dxtbx#256, where importing `h5py` before `dxtbx` could cause errors reading eiger files (because the plugin environment variable was only read on first load).

This patch uses the [H5PL](https://portal.hdfgroup.org/display/HDF5/Plugins) plugin API to make sure the correct path is set, even if h5py is imported first.

Notes:

- [`h5py.h5pl.append`](http://api.h5py.org/h5pl.html#h5py.h5pl.append)/[`H5PLappend`](https://portal.hdfgroup.org/display/HDF5/H5PL_APPEND) doesn't seem to work (at least not on my HDF5 1.10.6). It adds the path to the list, but HDF5 does not seem to read it for plugins, so am prepending instead.
- I wanted to avoid loading h5py immediately on import dxtbx - so I've kept the logic in the root __init__.py but only call it on FormatHDF5 initialization. I'm ambivalent about this arrangement though, so could easily be persuaded to change it if anyone is offended by it.
- We were planning to switch the legacy behaviour to a more visible UserWarning on 2020-11-30. It's close enough, let's do that now.

### CODE REVIEW

**Comment by Anthchirp** [comment]
> I wanted to avoid loading `h5py` immediately on `import dxtbx` - so I've kept the logic in the root `__init__.py` but only call it on `FormatHDF5` initialization

This one is easy. If h5py is already loaded (check sys.modules), do what you do. If it isn't loaded, update `HDF5_PLUGIN_PATH`

> Warning

That only makes sense if we've settled on a working mechanism. Judging from the number of recent pull requests we are not there yet. Vote to extend the deadline by 2 weeks.

**Comment by ndevenish** [comment]
> That only makes sense if we've settled on a working mechanism. Judging from the number of recent pull requests we are not there yet. Vote to extend the deadline by 2 weeks.

It's somewhat disconnected from the overall problem because that part is only related to the version of `hdf5-external-filter-plugins`, it was more of a "so we don't forget, while I am here" change. Happy to retain the non-deprecation.

**Comment by ndevenish** [comment]
> This one is easy. If h5py is already loaded (check sys.modules), do what you do. If it isn't loaded, update `HDF5_PLUGIN_PATH`

It feels dangerous, but I guess it's slightly less intrusive.

**Comment by ndevenish** [comment]
Okay, so now it looks to see if `h5py` is loaded, and if it isn't, it uses the environment variable. Otherwise it imports it itself and uses the plugin API.

**Comment by ndevenish** [comment]
I'm reluctant to push back the changing of the `DeprecationWarning` → `UserWarning` because if we're intending on removing this in 3.2 we've got a relatively fixed length of time to broadcast the warning to people.

**Pull request merged**
