### PR TITLE
Load before heat death

### PR DESCRIPTION
**Pull request by graeme-winter**
Having looked at the loading of "proper" still image sets I found where the time was going. 

Even if we have one image set in the experiment list, the set was duplicated NN times because of the key on (imagset, scan) in the cache code. Working around this in the kinda-sorta stupid way which is in this branch makes things load in finite time. 

N.B. this still works against imageset-experiment-iterator branch in dials, though this is not strictly necessary. 

I do not think this code is worthy of merging, but it encodes some information - a map of the onion mines, if you like. 

#info @rjgildea @ndevenish @dagewa

### CODE REVIEW

**Comment by graeme-winter** [comment]
At the moment there is still `raw_imagesets` and `imagesets` cached in here - I do not think the latter is actually used but before retiring would like input on this. 

Other than that I think this is actually useful - it does correctly cache the imagesets which means opening an experiment list pointing to large number of still images referenced against one imageset with different scans _works_.

**Comment by graeme-winter** [comment]
@ndevenish your commit makes sense - I could not work out what it was good for but felt I should not remove that stuff while I was there. On balance better to remove - behaviour seems to remain the same for me.

**Comment by ndevenish** [comment]
I can't think of any reason why imagesets would need to be keyed by scan? Even in cases where several scans point to same imageset?

Reasoned that it's probably supporting old behaviour, and it's a bad bug for the topology change.

**Comment by jmp1985** [comment]
I honestly can't remember why I used the scan as a key. Nick's suggestion that it was due to some old behaviour is probably true but I see no reason to keep the current behaviour so I think removing it is probably best.

**Comment by graeme-winter** [comment]
I think this is ready for review

**Comment by graeme-winter** [comment]
With last couple of commits 

```
Results (204.88s):
     961 passed
      13 skipped
```

from dials pytests

```
Results (74.38s):
     535 passed
       3 xfailed
      10 skipped
```

in dxtbx => ready for review now

**Comment by graeme-winter** [comment]
Adding @phyy-nx  as reviewer as this touches on still wrangling

**Comment by graeme-winter** [comment]
Comments above - I think this is now something which should end up being merged - though some attention may be needed to improve the documentation of what was learned here.

**Comment by phyy-nx** [comment]
Sorry, what was the command to trigger this code?  It looks like it's in the dictionary stuff (from_dict), which I thought was part of deserialization of an experiment list json, right?

In other words, this is after dials.import <big h5 file>, right?

**Comment by graeme-winter** [comment]
> Sorry, what was the command to trigger this code? It looks like it's in the dictionary stuff (from_dict), which I thought was part of deserialization of an experiment list json, right?
> 
> In other words, this is after dials.import , right?

Good point - that all happens in https://github.com/dials/dials/pull/1014

Importing a sequence of experiments which all point to the same underlying imageset/sequence allowing the structure to be correctly set at import but loading / processing be performed efficiently.

**Comment by rjgildea** [comment]
I haven't had chance to look at the changes in detail yet (I plan to do so after lunch), but it does strike me that presumably this changes the behaviour of imagesets in some way, but it seems that this new behaviour isn't covered by any new tests? Without any new tests, how are we supposed to prevent regression of the new behaviour in future? Also it would be nice to see explicit tests in dxtbx for the corner cases identified in e592774 and 9b37fd7.

**Comment by graeme-winter** [comment]
This should not change behaviour for image _sets_ only sequences. I am not entirely sure how to write the tests for this as well - could do with some input on this. 

It would be very nice (indeed: a reasonable expectation) to have 100% of the expected behaviour for dxtbx be covered by dxtbx tests, and I support the effort for this. Same for dials really.

**Comment by rjgildea** [comment]
I think some of the logic in dials/dials#1014 probably belongs somewhere in dxtbx:
https://github.com/dials/dials/pull/1014/files#diff-a8cbd704dbd46f905b3dbf4b37a8da3bR531-R557
I.e. doing the following currently gives me one experiment, whereas I understand the combination of these changes and those in dials/dials#1014 should give you 3 experiments (with a single shared imageset). The behaviour of dials.import and the code snippet below _should_ be equivalent.
```
from dxtbx.model.experiment_list import ExperimentListFactory
experiments = ExperimentListFactory.from_filenames(
    ['/Users/rjgildea/tmp/118/Puck3_10_1_000%i.cbf.gz' %i for i in range(1, 4)]
)
```

**Comment by graeme-winter** [comment]
> I think some of the logic in [dials/dials#1014](https://github.com/dials/dials/pull/1014) probably belongs somewhere in dxtbx:
> https://github.com/dials/dials/pull/1014/files#diff-a8cbd704dbd46f905b3dbf4b37a8da3bR531-R557
> I.e. doing the following currently gives me one experiment, whereas I understand the combination of these changes and those in [dials/dials#1014](https://github.com/dials/dials/pull/1014) should give you 3 experiments (with a single shared imageset). The behaviour of dials.import and the code snippet below _should_ be equivalent.
> 
> ```
> from dxtbx.model.experiment_list import ExperimentListFactory
> experiments = ExperimentListFactory.from_filenames(
>     ['/Users/rjgildea/tmp/118/Puck3_10_1_000%i.cbf.gz' %i for i in range(1, 4)]
> )
> ```

I'll have a look at moving teh logic over...

**Comment by graeme-winter** [comment]
At the moment this implementation is duplicated across dials.import and `dxtbx.model.experiment_list.ExperimentListFactory.from_filenames()` - I will look to see if I can make this share the same.

**Comment by graeme-winter** [comment]
#info I would like to see this merged real soon

**Pull request merged**
