### PR TITLE
Add codecov coverage badge to README

### PR DESCRIPTION
**Pull request by ndevenish**
Do we want this?

### CODE REVIEW

**Comment by Anthchirp** [comment]
this == [Coverage](https://codecov.io/github/dials/dxtbx?branch=master)

hmm looks a bit red, not sure we want to show this :smile:

**Comment by ndevenish** [comment]
Consider it motivation to improve!

**Comment by rjgildea** [comment]
Yes please, and dials too :)

**Comment by jmp1985** [comment]
+1 for having this

**Comment by Anthchirp** [comment]
7 days and only positive feedback -> merge

**Comment by Anthchirp** [comment]
except need to press green button instead of grey button

**Pull request merged**
