### PR TITLE
Ensure format instance is cached when first read

### PR DESCRIPTION
**Pull request by rjgildea**
Use `cls.get_instance()` rather than directly calling the class constructor in order to ensure that the format instance gets
cached to avoid re-instantiating the class the first time we call `imageset.get_{raw,corrected}_data()`.

Explicitly reset the cache before calling `cls.get_instance()` to force the format class to be re-instantiated if the process has
seen the current file previously. This is necessary in order to support live per-image analysis on HDF5/SWMR files.

For every call to the PIA service/[work](https://github.com/dials/dials/blob/23f63a7a1f250c5c12179480024b061e41e5db48/command_line/find_spots_server.py#L71-L260) function, a new format instance in created at this point here, via calling the class constructor directly:

https://github.com/cctbx/dxtbx/blob/219e0c79b12fd1c13f9608a12b90089434cd7624/format/FormatMultiImage.py#L161

However, this format instance is not cached within the format class. When `imageset.get_corrected_data()` is called from within spotfinder, this goes via the `Reader.read()` method, which doesn't call the class constructor directly, but goes via `format_class.get_instance()` which does handle caching:

https://github.com/cctbx/dxtbx/blob/219e0c79b12fd1c13f9608a12b90089434cd7624/format/FormatMultiImage.py#L47-L49

https://github.com/cctbx/dxtbx/blob/219e0c79b12fd1c13f9608a12b90089434cd7624/format/Format.py#L265-L275

The first time a process sees a given file, this means a format instance gets constructed twice - once when the class constructor is called directly, and again when the `get_instance()` classmethod is called.
The second time a process sees the given file, a format instance is created once when the class constructor is called directly, but this is then immediately thrown away and the previously cached format instance is used within the `imageset.get_corrected_data()` call.

For live per-image analysis of HDF5/SWMR files, this previous format instance has the [`DataFactory`](https://github.com/cctbx/dxtbx/blob/219e0c79b12fd1c13f9608a12b90089434cd7624/format/nexus.py#L1320-L1411) and resulting hdf5 datasets in the state they were when the file was first seen by the current process, i.e. not reflecting the current state of the dataset. With the changes in this PR, the new instance of `DataFactory` (which was already constructed anyway, before being thrown away) will be used when calling `imageset.get_corrected_data()` meaning that per-image analysis can now view data that was written after the process first saw a given image file.

### CODE REVIEW

**Comment by Anthchirp** [comment]
Looking at this I am wondering if the solution shouldn't go the other way around:

> Explicitly reset the cache before calling `cls.get_instance()` to force the format class to be re-instantiated if the process has
> seen the current file previously. This is necessary in order to support live per-image analysis on HDF5/SWMR files.

This sounds to me like `get_instance()` is misbehaving and shouldn't be used at all - deprecated and removed - and instead we should be looking at not constructing format classes needlessly. 🤔

**Comment by graeme-winter** [comment]
> Looking at this I am wondering if the solution shouldn't go the other way around:
> 
> > Explicitly reset the cache before calling `cls.get_instance()` to force the format class to be re-instantiated if the process has
> > seen the current file previously. This is necessary in order to support live per-image analysis on HDF5/SWMR files.
> 
> This sounds to me like `get_instance()` is misbehaving and shouldn't be used at all - deprecated and removed - and instead we should be looking at not constructing format classes needlessly. 🤔

Totally agree with this sentiment, however one is a minimally invasive fix, the other is a substantial body of work which is probably a good idea, but not strictly necessary in the immediate timeframe?

**Comment by Anthchirp** [comment]
Agreed, I'll move the comment.

**Comment by rjgildea** [comment]
@dwpaley I think this also fixes https://github.com/cctbx/dxtbx/issues/245 (at least the [xfailing test you added](https://github.com/cctbx/dxtbx/commit/a701a402a3b425ede80cac18409a373ab1992299) now passes with this PR.

**Comment by dwpaley** [comment]
Richard, this is great. I recall the odd multiple calls to `FormatXXX._beam` that were apparent in  `test_single_file_indices` as well, clearly because the format class was being instantiated twice as you show here. Thanks for flagging me. I'll close #245 when this is merged.

**Review by dwpaley — APPROVED** [review]

**Review by phyy-nx — APPROVED** [review]
Looks good.  I'm working on getting the xfel_regression instructions ready.  I'll post them when I have them.

**Review by Anthchirp — APPROVED** [review]

**Pull request merged**
