### PR TITLE
Nxmx mask

### PR DESCRIPTION
**Pull request by dwpaley**
This borrows the FormatNexus implementation of `get_static_mask` for FormatNXmx. In the existing implementation, the entire array of masks in the h5 file was dereferenced in the format `start` method, which could hang forever on a large file with a mask for every image.

### CODE REVIEW

**Comment by dwpaley** [comment]
still got some bugs to work out

**Comment by dwpaley** [comment]
This is ready for review but requires nxmx branch `pixel_mask_single`.

**Comment by ndevenish** [comment]
Oh, I think I jumped here. It'll need the nxmx conda-forge package to update, so this will immediately fail.

**Comment by ndevenish** [comment]
The last time I can find record of us discussing this, [2023-06-15](https://dials.github.io/kb/core/2023-06-15#nxmx), we concluded:
- Should clarify the meaning of static on the function docstring
- You'd check that this PR still fulfils the requirements of the data processing that was intended by these changes

Are you happy with these points? Is this otherwise ready to go?

**Pull request closed without merging**
