### PR TITLE
Detector format for CHESS ID7B2 Eiger2 16M

### PR DESCRIPTION
**Pull request by spmeisburger**
Copied from https://github.com/FlexXBeamline/dials-extensions/blob/main/dials_extensions/FormatNXmxEigerFilewriterCHESS.py

This format addresses two issues with the FormatNXmxEigerFilewriter base class:

1. Recent firmware upgrade for Eiger2 16M which reverses image dimensions (see PR #676)
2. Reversed spindle axis at 7B2

### CODE REVIEW

**Comment by biochem-fan** [comment]
Once PR #676 is merged, `_get_nxmx` is not necessary, is it?

**Comment by spmeisburger** [comment]
@biochem-fan that's correct, `_get_nxmx` would be redundant with base class proposed in PR #676, and could be removed if PR #676 goes in first.

**Comment by biochem-fan** [comment]
@spmeisburger #676 got merged.

**Comment by spmeisburger** [comment]
Thanks @biochem-fan, I rebased on main and removed the duplicated feature, waiting for checks to complete...

**Comment by ndevenish** [comment]
This needs to be updated to latest to check it still works, but unfortunately the branch is set to not allow edits. We're happy to reopen/reconsider if you want to do the updating, or turn on edits.

**Pull request closed without merging**
