### PR TITLE
Environment variable for build-folder install - sticky

### LINKED ISSUE #473: Can we make CCTBX_INSTALL_PACKAGE_BUILD "sticky"
Just chatting with @phyy-nx  and he came up with a niggle

Following on from... 

https://github.com/cctbx/dxtbx/pull/471

is there a way to make `CCTBX_INSTALL_PACKAGE_BUILD` sticky so that if you source the environment again _without_ having exported that you don't then find the original behaviour when `libtbx.refresh` is run. 

@phyy-nx  recognised that this was something he missed in the original discussion 😉

I guess saving this in the `dials` environment file would do the job?

### PR DESCRIPTION
**Pull request by ndevenish**
As an expansion of https://github.com/cctbx/dxtbx/pull/471 - it was raised that the behaviour wasn't sticky on reconfigure. Additionally, we've been asked to invert the behaviour, making the readonly base directory behaviour the default, and only install using the standard python packaging behaviour if there is an environment variable set (which we will do in DIALS bootstrap before merging this change).

So:
- Readonly base will now be assumed and dxtbx will be installed into the build/ directory
- .... unless the `TBX_INSTALL_PACKAGE_BASE` environment variable is export on configuration
- After which the setting will be remembered across build reconfiguration.

Fixes #473

---
Previous contents

~As an expansion of https://github.com/cctbx/dxtbx/pull/471 - an issue was raised in https://github.com/cctbx/dxtbx/issues/473 that you needed to have the environment variable also set on reconfiguration, and the libtbx refresh script doesn't know the difference between which bootstrap environment it came from.~

~Has several checks, and goes into read-only-base mode if any of:~
- ~`CCTBX_INSTALL_PACKAGE_BUILD` is set an non-empty (changed from set/unset so it's easier to clear if needed to).~
- ~The `dxtbx/src` folder is in the `libtbx.env.pythonpath` list of additional locations. It's assumed that if this path had been manually injected before, that dxtbx was configured in read-only-base mode. Unlike the first time configuration is performed, this is _at least_ the complete (previous) environment, so the environment fetch bug workaround is not necessary here.~
- ~The file `build/dxtbx/CCTBX_INSTALL_PACKAGE_BUILD` exists. This is touched by the initial install~
- ~The base environment is not writable (the initial check)~

~Fixes #473~

### CODE REVIEW

**Comment by ndevenish** [comment]
I'm currently running your diagnostics tests but I can't work out how to get it to use mamba so it's taking an extremely long time.

**Comment by ndevenish** [comment]
I've switched it to just dropping a marker file `build/dxtbx/CCTBX_INSTALL_PACKAGE_BUILD`. If this is present on reconfigure, then it acts as though the environment variable is set. This survives over reconfigures.

I ran the steps from #473 and got no changes at all - but I didn't have iota checked out (although it thought the empty folder was still a module) and xia2 didn't get configured. So it looks like this is working to satisfaction?

**Comment by ndevenish** [comment]
Okay, this test has been inverted now. We need to make some bootstrap changes before this is merged because unlike previously read-only installs (in which case the behaviour was preserved) this will change the default for existing installations and thus install a second copy of metadata.

**Comment by ndevenish** [comment]
Okay, to attempt to somewhat preserve existing behaviour and the complexity of inverting this check (from _read-only if base is read-only_, adding "OR environment variable"; instead going from "_read only if base is read only_" to "_read only even if base is writable UNLESS environment variable_")  - this is a more complicated change than I had anticipated. Additionally, we need the bootstrap changes from https://github.com/dials/dials/pull/1997 to be in before the tests here in dxtbx (which uses a copy of bootstrap) work, and instruct all existing users to take steps in order to preserve the existing behaviour is inherently more complicated.

Thus, we probably now won't be able to get this stuff merged until next week.

**Comment by phyy-nx** [comment]
Sounds good.  Thanks.

**Comment by Anthchirp** [comment]
Another option may be to check for the presence of the `./dials` file on the top level, which already indicates a dials-bootstrap environment iirc.

**Pull request merged**
