### PR TITLE
use entry points in format registry

### PR DESCRIPTION
**Pull request by Anthchirp**
(note: you will need to run `make reconf` after updating your master branch to 8e77cf1 or later before you can test this. That commit registers entry points and since it does not change other behaviour I pushed it directly to master)

Instead of using metaclasses to find image format classes we now use entry points.

A number of related registry lookup methods were deprecated or removed.

A directed acyclical graph is constructed from all registered image format classes, and traversed for a given image file. We walk down the DAG is a format class says it understands the file. Multiple formats on the same level may understand the file, but they must then converge again into a single node using multiple inheritance.

We no longer eat exceptions from `understand()` methods. Similarly, when no matching format was found the datablock find_format methods now return `None` and no longer raise exceptions. In both cases the caller will need to deal with the situation appropriately.

I've run dxtbx and dials tests and everything still passes. There are a number of deprecation warnings outstanding in dxtbx and iotbx but these can be addressed later.

### CODE REVIEW

**Comment by graeme-winter** [comment]
Looks useful, gets away from mystery code 👍- metaclasses are fun but probably not a good solution

- please could you explain the mechanism for $end-user adding format class
- does his guarantee they form a DAG

I would also suggest @phyy-nx have a look

I can see the advantages, for example being able to fetch a format class by name rather than having to re-search (which could resolve a number of other problems)

**Comment by Anthchirp** [comment]
* DAG guarantee: This is guaranteed by virtue of Python not allowing you to do circular inheritance such as
```python
class A(B):
  pass

class B(A):
  pass
```
If no class can inherit from its children (and I would advise against hacking Python to allow this) then the set of all children of `Format` will automatically form a DAG.

* There is currently no end-user mechanism in place with this pull request. I can see two possible approaches:
  1. Put the custom format into a normal python package, which can be installed/updated/maintained independently.
  2. Create a command (eg. `dxtbx.install_format`) that can download and install a format class from a remote source, place it into eg. `dxtbx/contrib/` and set up appropriate entry points by creating a fake package using the same mechanism as `libtbx_refresh`.

**Comment by phyy-nx** [comment]
We have lots of custom format classes in ~/.dxtbx.  Will that mechanism
still be supported?

**Comment by Anthchirp** [comment]
This does not support format files that are not underneath an importable path. I am wondering - what do you use this for? Is it to selectively enable/disable format classes, or do you keep/develop format classes outside of source control? Or are those format classes able to co-exist with the dxtbx format classes but normally kept in another repository and do you merely use the `~/.dxtbx/` location as a means to activate them?

**Comment by graeme-winter** [comment]
Suspect custom formats which encode metadata from specific X-FEL runs e.g. (on this day we had this detector configuration) etc. 

Which is not wrong, and probably should not be in the main repo, so some alternative to this mechanism may be needed.

**Comment by phyy-nx** [comment]
All of the above, with the addition that users may not have write access to
their code (SBGrid installation for example, or a docker container at
NERSC), therefore they need a way to add their own format classes.  This is
a design specification from the beginning of dxtbx.

**Comment by Anthchirp** [comment]
So you do not use it to selectively enable/disable format classes, but as a means to install a pre-determined set of format classes that are not part of dxtbx in a specific scenario. 
I would still need to know where the format classes normally live, so whether they are individually downloaded or part of another code repository and whether they play nice with other existing format classes to advise on the best course of action.

**Comment by phyy-nx** [comment]
~/.dxtbx, and generally not part of a code repository.  When they have been
part of a code repository, I've softlinked that folder to ~/.dxtbx, but I
haven't done that in a while.

I'd rather not preclude the possibility of using ~/.dxtbx to disable/enable
format classes.  These classes are just part of the registry and do
whatever the registry can do, adding, disabling, or changing functionality
through object inheritance.

**Comment by Anthchirp** [comment]
Okay, not a problem. The `.dxtbx` directory can continue to be used when it is registered as a package. This does not require write access to the python base directory and needs 3 additional files in `.dxtbx`, specifically an empty `__init__.py`, a symlink `dxtbx_custom -> .` and a `setup.py`, and a command needs to be run whenever files are added/removed. Just tested this locally and it works. I'll attach a `setup.py` once I have written the auto-registration code.

On second thought this `setup.py` probably should go into `dxtbx/contrib` because other people may find it useful, too.

**Comment by phyy-nx** [comment]
So any existing ~/.dxtbx will not work after this pull request is merged.
A deprecation warning will be important.

**Comment by Anthchirp** [comment]
further, @dagewa has a use case where users may want to download and install specific format classes using a URL. So instead of making you play around with `setup.py` files I'll make a command line tool which does the registration directly and offers a download facility.

**Comment by ndevenish** [comment]
Other than implementation simplicity/purity/getting rid of magic, is there not some way that we can support both cases? Package registry clearly makes things easier to add via e.g. installing packages but assuming we're still going through the `Registry` object we can *also* have it search and import everything in `~/.dxtbx`, even if it's not a package?

I imagine a simple way for non-technicalish people to just add quick and dirty modified formatters is probably a valuable thing?

**Comment by phyy-nx** [comment]
Also, does registering an entry point imply writing to the build or source
folder somewhere?  I assume something is cached somewhere since this is
currently done in the libtbx.refresh.  Remember, the user may not have
write access, so registering entry points from ~/.dxtbx would not work in
that use case.

**Comment by graeme-winter** [comment]
IIRC a main benefit to this is we can save the class name and reconstruct the object without the registry search

Which would seem to be a good thing

It would also allow others to publish format classes via pip and have them work

The .dxtbx directory feature is a useful one but niche. The vast majority of users don’t add classes

The no write access to install use case is valid but I think a command line tool to register new formats is a good thing

**Comment by Anthchirp** [comment]
Yes, I already support all of the above. Commit incoming shortly.

**Comment by phyy-nx** [comment]
"we can save the class name and reconstruct the object without the registry
search"
"It would also allow others to publish format classes via pip and have them
work"

Can you help me understand these points more?  They sound compelling, but I
really have no idea what entry points are or why it's worth re-doing dxtbx
to use them.
Thanks :)

**Comment by ndevenish** [comment]
Entry points are basically a giant string-List[string] lookup dictionary that are tied to a package installation. Each package can register any number of them, and the meaning is up to the packages. e.g.
- `pip` uses the `console_scripts` entry point to find commands - you can point to a function in your code, and pip builds the dispatcher automatically - no need to worry about pathing, windows/linux differences etc (e.g. on windows it will create .exe files to launch your module automaticall)
- Pytest uses it to find plugins; this is why all you need to do is install a package and pytest can find them at runtime, efficiently and without having to e.g. scan the library paths for compatible packages: https://github.com/pytest-dev/pytest-xdist/blob/master/setup.py#L21-L23

We've started moving to it for registering different sorts of pluggable code modules. This is extending that metaphor to packages. Imagine e.g. nexus support being optional, and all you need to do is `pip install dials-nexus` to get everything you need, automatically registered.

Read-only code isn't a problem usually because you can install packages to a user path (`--user` in `pip install`).

**Comment by Anthchirp** [comment]
As mentioned at the start in issue #26 currently we currently import every format class and use metaclasses to enumerate formats. This effectively limits us to format classes in specific locations, ie. only dxtbx itself can define format classes, and users can format classes in their home directory. The latter is fine for people who know what they're doing, but a support nightmare for non-developers because it circumvents any versioning. With entry points every package declares what format classes it contains - dxtbx can declare this as well as _any_ other python package - and we just check the central registry.

You may also find the commit messages to https://github.com/cctbx/dxtbx/commit/8e77cf14eb157b13140af13ac8c6a72a12ada43e and https://github.com/cctbx/dxtbx/commit/8f44f4c250ee19402c9f6dfc90a459ddd03114f2 instructive.

We have been using entry points in dials for a long time already [to register profile and scaling models](https://github.com/dials/dials/blob/master/libtbx_refresh.py#L6-L17).

**Comment by ndevenish** [comment]
Just commenting to add that I was slightly off in that it's specified as string-string but it looks like it's actually enforced to be `string-<name = object path>` - for each entry point you specify, there is a name for the entry and a pointer to a python object by import path name somewhere in your module.

**Comment by Anthchirp** [comment]
This is how the command now works:

Given a FormatDummy.py:
```python
from __future__ import absolute_import, division, print_function

from dxtbx.format.Format import Format


class FormatDummy(Format):
    def understand(self):
        return False
```

```bash
$ dxtbx.show_registry | grep "Dummy\|TIFFeBIC"
$ rm ~/.dxtbx -r
$ dxtbx.install_format -u FormatDummy.py 
Copied /home/wra62962/FormatDummy.py to /home/wra62962/.dxtbx/FormatDummy.py
  found FormatDummy based on ['Format']

Format classes installed, format class registry updated.
$ dxtbx.show_registry | grep "Dummy\|TIFFeBIC"
    1    FormatDummy
$ dxtbx.install_format --u https://raw.githubusercontent.com/dials/dxtbx_ED_formats/master/FormatTIFFeBIC.py
Downloaded https://raw.githubusercontent.com/dials/dxtbx_ED_formats/master/FormatTIFFeBIC.py to /home/wra62962/.dxtbx/FormatTIFFeBIC.py
  found FormatDummy based on ['Format']
  found FormatTIFFeBIC based on ['Format']

Format classes installed, format class registry updated.
$ dxtbx.show_registry | grep "Dummy\|TIFFeBIC"
    1    FormatDummy
    1    FormatTIFFeBIC
$ ls -la ~/.dxtbx/
total 84
drwxrwxr-x.   3 wra62962 wra62962  4096 Jun  6 19:06 .
drwxr-xr-x. 156 wra62962 wra62962 40960 Jun  6 19:05 ..
lrwxrwxrwx.   1 wra62962 wra62962    21 Jun  6 19:05 dxtbx_custom -> /home/wra62962/.dxtbx
drwxrwxr-x.   2 wra62962 wra62962  4096 Jun  6 19:06 dxtbx_custom.egg-info
-rw-rw-r--.   1 wra62962 wra62962   181 Jun  6 19:05 FormatDummy.py
-rw-rw-r--.   1 wra62962 wra62962   682 Jun  6 19:06 FormatDummy.pyc
-rw-rw-r--.   1 wra62962 wra62962  6202 Jun  6 19:06 FormatTIFFeBIC.py
-rw-rw-r--.   1 wra62962 wra62962  6405 Jun  6 19:06 FormatTIFFeBIC.pyc
-rw-rw-r--.   1 wra62962 wra62962     0 Jun  6 19:05 __init__.py
-rw-rw-r--.   1 wra62962 wra62962   133 Jun  6 19:06 __init__.pyc
-rw-rw-r--.   1 wra62962 wra62962   533 Jun  6 19:06 setup.py
```

**Comment by nksauter** [comment]
We will want to preserve the ability to use ~/.dxtbx to run the examples in
our published papers, i.e., https://doi.org/10.1107/S1600577518004873 ,
pointing to the repo https://github.com/nksauter/fv5080.
Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division

**Comment by Anthchirp** [comment]
For this example the format class would be installed with
`dxtbx.install_format -u https://raw.githubusercontent.com/nksauter/fv5080/master/FormatHDF5ImageDictionary.py`

**Comment by phyy-nx** [comment]
" we currently import every format class and use metaclasses to enumerate
formats."

Does this implementation of entry points reduce the number of imports
during runtime?  If so, how?

**Comment by Anthchirp** [comment]
The implementation as it stands right now does not reduce the number of imports, as every file containing a format class is still imported to construct the DAG. If you don't need the DAG - when you already know the correct format class - then you could bypass all the importing.

I am currently playing with encoding the DAG itself in entry points, meaning that format classes are only imported when needed, and non-matching subgraphs will never be imported (eg. would only import any of `FormatTIFFRayonix*` if `FormatTIFF` matches, but never when `FormatCBF` matches)

**Comment by phyy-nx** [comment]
That sounds great.  Either way, thanks all for the explanations.  Very
helpful.

**Comment by Anthchirp** [comment]
This encodes the DAG in the entry point definitions. An (unscientific) test run using `dials.find_spots` on a `.cbf` file showed the number of opened files go down from 1673 to 1506 (measured by `strace` - successful open() calls).

dxtbx tests pass, local testrun showed no regressions in iotbx, dials, or xia2 (with `--regression`).
Planning on adding another release note commit and merging this early next week.

**Comment by phyy-nx** [comment]
Awesome

**Comment by asmit3** [comment]
@Anthchirp I tried doing the FormatDummy.py installation at SACLA using the instructions you gave above in a comment and got an error.  Any idea what might be happening ?

```
(myEnv) [amorville@hpc01-clst05 ~]$ dxtbx.install_format -u FormatDummy.py 
Copied /home/amorville/FormatDummy.py to /home/amorville/.dxtbx/FormatDummy.py
  found FormatDummy based on ['Format']
Traceback (most recent call last):
  File "/home/amorville/software/cctbx.xfel/build/../modules/dxtbx/command_line/install_format.py", line 161, in <module>
    run()
  File "/home/amorville/software/cctbx.xfel/build/../modules/dxtbx/command_line/install_format.py", line 156, in run
    install_package(home_location, format_classes)
  File "/home/amorville/software/cctbx.xfel/build/../modules/dxtbx/command_line/install_format.py", line 78, in install_package
    print_stdout=False,
  File "/home/amorville/software/cctbx.xfel/newconda3/envs/myEnv/lib/python2.7/site-packages/procrunner/__init__.py", line 387, in run
    stderr=subprocess.PIPE,
  File "/home/amorville/software/cctbx.xfel/newconda3/envs/myEnv/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/amorville/software/cctbx.xfel/newconda3/envs/myEnv/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: coercing to Unicode: need string or buffer, LocalPath found
```

**Comment by ndevenish** [comment]
Currently on Shinkansen so not in a place to delve right now, but my first reaction is that it looks like a pathlib object is being passed to python 2s subprocess somewhere. Maybe as part of python 3 changes?

**Comment by asmit3** [comment]
Is this the only way to add new or custom format classes ? I don't hit a breakpoint when I put it in dxtbx/format (adding a breakpoint in the understand method) so if I add a new format class in dxtbx/format, that also needs to be registered ?

**Comment by ndevenish** [comment]
You need to libtbx.refresh for new formats in dxtbx, IIRC

Tracing the origin of the error shouldn’t be too difficult though

**Comment by asmit3** [comment]
Ok, I was able to use the Dummy format class by moving the file to dxtbx/format/ and then running libtbx.refresh. It would be great though if the dxtbx.install_format feature works for .dxtbx folder because I am working on a custom format class that does not really belong to dxtbx/format and so this is mostly a hack for this beamtime.

**Comment by ndevenish** [comment]
So, this problem is caused by using an out-of-date procrunner. @bkpoon, It looks like the https://github.com/cctbx/cctbx_project/blob/master/libtbx/auto_build/conda_envs/cctbx_py27_linux-64.txt hasn't been updated for a few months?

**Comment by Anthchirp** [comment]
Yes, this was included in cctbx/cctbx_project#336

**Comment by Anthchirp** [comment]
This pull request also declared the correct dependency in libtbx_config. Does this mean you didn't `make reconf` for 26 days?

**Comment by asmit3** [comment]
@Anthchirp - I was running it off a fresh installation of DIALS but since on SACLA hpc we can't pull stuff from outside, the dependencies remain the same as specified in the conda package list. @ndevenish pointed out the issue might be with procrunner version as the conda list specifies it to be 0.9 while libtbx_config dependencies show it to be 1.0.2. This is also the issue with package_defs

**Comment by ndevenish** [comment]
So I think it's fine in the conda list because it doesn't specify: https://github.com/cctbx/conda_build/blob/e548529e99d6377992ff91e6e7b57aaa985ba7d5/cctbx_dependencies/meta.yaml#L71 so should be picked up fine

It's still 0.9.1 in package_defs.py: https://github.com/cctbx/cctbx_project/blob/47ee49fe76188f0854e7ba0cae0c672a1e83efd7/libtbx/auto_build/package_defs.py#L85, but 
- I think this doesn't matter because as I understand it you never use base install for entry-only environments - just conda?
- It doesn't matter for us as any normal build will get the updated dependencies as part of build
- There seems to be an open pull request for updating this anyway https://github.com/cctbx/cctbx_project/pull/336

So it just looks like the cached file lists; https://github.com/cctbx/cctbx_project/blob/master/libtbx/auto_build/conda_envs/cctbx_py27_linux-64.txt - I don't know the update policy for these?

**Comment by Anthchirp** [comment]
Yeah, I put in that pull request for package_defs back in May, but as these things are contentious I didn't push for it to be merged and nobody in cctbx_project has shown any interest so far. Thanks to the dependency declarations we do not rely on these changes going through into cctbx_project any more, so I personally don't care much if/when this is merged. The pull request is pure courtesy anyway since the agreement was that package_defs (and conda environment) is kept up to date by LBL folks.

**Pull request merged**
