### PR TITLE
Don't set batch offset when creating image sequences

### PR DESCRIPTION
**Pull request by jbeilstenedmands**
This should now be unnecessary following https://github.com/cctbx/dxtbx/pull/634 and related changes.

Removes an unintended use of the batch offset property

Fixes https://github.com/dials/dials/issues/1347

Will not be merged without thorough testing and discussion.

### CODE REVIEW

**Comment by ndevenish** [comment]
Holding off for more testing

**Comment by dwpaley** [comment]
Running XFEL tests here:
https://github.com/cctbx/cctbx_project/tree/test_dxtbx_662

**Comment by dwpaley** [comment]
Currently all good with respect to XFEL CI tests :)

**Comment by jbeilstenedmands** [comment]
I have run the dials and xia2 tests, however some of the `xia2.ssx` tests are failing with this change, due to the use of the batch offset in `dials.ssx_integrate` when slicing an imageset.
I need to investigate further whether I can work around this, I thinkn in theory it should be possible.

**Pull request closed without merging**
