### PR TITLE
Py3 CBFs

### PR DESCRIPTION
**Pull request by phyy-nx**
This does much of the work to fix CBFs in py3.

Main changes:
- Read the cbf header in unicode. This allows us to keep many string literals in the format classes unchanged.
- Fix up file reading for mini cbfs
- Change string literals involved with CBF fulls to byte strings since that's what pycbf uses now.

See #36.

With this, the number of dxtbx tests failing goes down from 382 to 349.

### CODE REVIEW

**Comment by Anthchirp** [comment]
Thank you!

I am wondering. Graeme mentioned CBF headers are per definition ASCII (iirc), so would it not make sense to identify the header portion, convert that to text and then treat it as text from there?

(Am neither a CBF specialist, nor aware of possible consequences regarding cbflib...)

**Comment by phyy-nx** [comment]
Good question.  There are two kinds of CBFs, Fulls and Minis.  The problems are different for each.  

First, in FormatCBF, the understand method is a read of exactly 6 bytes, so this has to be done in binary. See
https://github.com/cctbx/dxtbx/pull/37/files#diff-c8abc59e2ddb31875894a75fe9b7c202L26

The understand methods of FormatCBFMini and FormatCBFFull both need to read the cbf header.  We read the header in bytes, searching for a specific string that marks the end of the header.  Then we can decode this into unicode and build the cbf header dictionary. So this is as you describe.  See:
https://github.com/cctbx/dxtbx/pull/37/files#diff-c8abc59e2ddb31875894a75fe9b7c202L42

(Note, it's possible that that open statement could be 'r' instead of 'rb', but I think the encoding and error method would also need to be specified in the open call. Doesn't really matter, but it seems likely reading in binary is faster)

For Mini's that's the whole story.  We convert the header to unicode so the string literals are nice and we read the data in binary mode.

However, Full cbfs use pycbf directly.  The default for pycbf in py3 when returning any data as a string is to decode it into unicode.  This includes reading pixel data.  In python we'd then have to encode the unicode strings into bytes, which all seems dangerous and time-consuming.  I added a flag that changed the SWIG C functions of pycbf to use byte strings instead of unicode strings.  No encoding/decoding needed when reading the pixel data.  However, because of this, all of the literals used when reading Fulls had to be changed to byte strings.
See
https://github.com/cctbx/cctbx_project/blob/master/cbflib_adaptbx/SConscript#L110
https://github.com/cctbx/dxtbx/pull/37/files#diff-7915b2c8b8cb0397439f998cbea1a066L82

Hopefully that answers the question?

**Comment by Anthchirp** [comment]
Yes, thank you. I am not entirely sure whether we should go for an `ignore` or `replace` strategy with invalid characters and slightly tend towards `replace`. I'll do some refactoring and fix up the `FIXME` in `FormatCBF.py`

**Comment by Anthchirp** [comment]
I have a question about the MiniCBF reading logic:
In `def read_cbf_image(self, cbf_image):` we [read in the file `cbf_image`](https://github.com/cctbx/dxtbx/pull/37/commits/2a0e668c6a7283501dfb70a48666805c3932a2ef#diff-66265e4d4484884c351a8641c0004879L252) to parse the header, and then we [read in the file `self._image_file` and mangle it a bit](https://github.com/cctbx/dxtbx/pull/37/commits/2a0e668c6a7283501dfb70a48666805c3932a2ef#diff-66265e4d4484884c351a8641c0004879L289) to read the pixel values.

Can they actually be different files? Or can this be changed to a single file operation?

**Comment by phyy-nx** [comment]
> I have a question about the MiniCBF reading logic:
> In `def read_cbf_image(self, cbf_image):` we [read in the file `cbf_image`](https://github.com/cctbx/dxtbx/pull/37/commits/2a0e668c6a7283501dfb70a48666805c3932a2ef#diff-66265e4d4484884c351a8641c0004879L252) to parse the header, and then we [read in the file `self._image_file` and mangle it a bit](https://github.com/cctbx/dxtbx/pull/37/commits/2a0e668c6a7283501dfb70a48666805c3932a2ef#diff-66265e4d4484884c351a8641c0004879L289) to read the pixel values.
> 
> Can they actually be different files? Or can this be changed to a single file operation?

This does seem like a bug.  Either read_cbf_file shouldn't take a filename parameter or it shouldn't use _image_file.  Using both doesn't make sense.  In fact, maybe it should be a static method.

**Comment by Anthchirp** [comment]
I've `grep`ped across cctbx_project, dxtbx and dials and it looks like `read_cbf_image` is only used within the same format class, so I'll make it a private method and remove its parameter.

**Comment by Anthchirp** [comment]
So I've rewritten the function, but noticed we currently have 0 test coverage on the `if` branch that is re-reading the file, and I don't know enough about the `read_int32(streambuf())` magic, so I decided to leave that as it is for now.

I've cleaned up the commit history, grouping related changes together.

@ndevenish sounded like he had a suggestion on the unicode handling. I've added him as a reviewer so he can take a look if he can find the time. Otherwise this is good to go.

**Comment by phyy-nx** [comment]
👍

**Comment by ndevenish** [comment]
I'm concerned that lots of fields that look like they should be ASCII are specified as byte-strings; It seems unoptimal versus fixing PyCBF. There's also a lot of encode/decode - are these all on the boundary between pycbf?

There's also the option of latin-1 if you want to allow ascii-invalid fields but don't want to allow multibyte characters.

In any case, some of this is a feature of rather creaky old format code, and can all be fixed and tidied up later, so I have no objection to this going in now.

**Pull request merged**
