### PR TITLE
Move compression and decompression routines into dxtbx

### PR DESCRIPTION
**Pull request by graeme-winter**
3rd time lucky...

### CODE REVIEW

**Comment by graeme-winter** [comment]
Selecting draft appears to reset target ...

**Comment by graeme-winter** [comment]
Question to reviewers: would it aid readability to express e.g. 

```
    if ((-32767 <= delta) && (delta < 32768)) {
      s = (short)delta;
      b = ((u_s *)&s)[0].b;

      if (!le) {
        byte_swap_short(b);
      }

      packed.push_back(b[0]);
      packed.push_back(b[1]);
      current += delta;
      continue;
    }
```

in hex?

**Comment by graeme-winter** [comment]
Attempts to fix SConscript in keeping with `dials` one have now completely broken it \o/

Will revisit Monday

**Comment by graeme-winter** [comment]
> Attempts to fix SConscript in keeping with `dials` one have now completely broken it \o/
> 
> Will revisit Monday

Wait, what? This fixed it 🤔

**Comment by graeme-winter** [comment]
OK, something weird here. 

The tests were failing for me, passing in here. 

I thought was my build being skewed so I have just made a clean bootstrap and ... still fails. 

Lots of 

```
E       Boost.Python.ArgumentError: Python argument types in
E           Scan.__init__(Scan, tuple, tuple, double, double, int, bool)
E       did not match C++ signature:
E           __init__(boost::python::api::object, scitbx::vec2<int> image_range, scitbx::vec2<double> oscillation, scitbx::af::shared<double> exposure_times, scitbx::af::shared<double> epochs, int batch_offset=0, bool deg=True)
E           __init__(boost::python::api::object, scitbx::vec2<int> image_range, scitbx::vec2<double> oscillation, int batch_offset=0, bool deg=True)
E           __init__(_object*, dxtbx::model::Scan)
E           __init__(_object*)
```

why is this not failing centrally?

**Comment by Anthchirp** [comment]
covered by tests skipped here because dials_regression?

**Comment by graeme-winter** [comment]
I have a clean build with no dials regression, so that is quite odd. Suspect it would fail in a clean build, but maybe the route for bootstrapping to where it got to with incremental builds is such that it has something built & linked. 

Guess no-op changes to force rebuild could flush out some errors?

**Comment by Anthchirp** [comment]
You can force flushed cache builds by resetting the date in line 2 of `.azure-pipelines.yml`

**Pull request merged**
