### PR TITLE
Break the DIALS/xfel circular dependency

### LINKED ISSUE #239: dxtbx/xfel circular dependency
_(issue carried over from [discussion in DIALS core meeting](https://dials.github.io/kb/core/20201015#dxtbx--xfel-dependencies))_

Do we need to resolve the dxtbx/xfel circular dependency?  My personal opinion is that it's not really a big deal as we can (and have) made the xfel imports conditional and we have ensured testing happens in the context where both packages are configured.  Regardless, here's a good place to discuss whether we need to do anything and the issue generally.

If it we were to refactor dxtbx and cctbx_project/xfel to remove the circular dependency, here are the details, specifically the dependencies in dxtbx on xfel:

1. FormatXTC*: these depend on cspad_tbx, rayonix_tbx, and cspad_cbf_tbx.  Lots of functionality for treating psana data is in these xfel libraries.  
2. Same with FormatPYmultitile.py and FormatPYunspecified.py
3. cbf_writer uses cbf creation code in xfel
4. radial_average uses C++ code in xfel to average the pixels into bins
5. image2pickle: uses cspad_tbx
6. detector_superpose: uses a function iterate_detector_at_level in xfel.command_line.cspad_detector_congruence

Probable best courses of action:
1. Move FormatXTC* to a new xfel/format folder and register them it in xfel/libtbx_referesh.py.  Simplest, but has the disadvantage of having Format classes in multiple locations.  Understand this is already the case for some ED Format classes?
2. Same as 1.
3. Don't know what to do here as I want the cbf_writer in dxtbx but the cbf creation code probably shouldn't leave xfel.  Might still be a way to split libraries some to make it work.
4. I don't think the radial_average C++ code is used in xfel.  Moving it to dxtbx is probably fine.
5. image2pickle should be deprecated
6. Probably detector_superpose should go to xfel as it's not really been used much as a far as I know outside of myself.

Again, I view this as pretty low priority, but I welcome feedback :)

### PR DESCRIPTION
**Pull request by phyy-nx**
DIALS and dxtbx have had dependencies on cctbx_project/xfel, and vice versa. This PR is one of 8 that will break the cyclic dependency.

Notably for dxtbx, this specifically removes:
`pytest.importorskip("xfel")`

For more detail, see cctbx/cctbx_project#872 and dials/dials#2404 (placeholder)

Closes #239

### CODE REVIEW

**Comment by ndevenish** [comment]
Explicitly requires https://github.com/cctbx/cctbx_project/pull/872 to be merged

**Comment by ndevenish** [comment]
Otherwise looks reasonable 👍

**Review by ndevenish — APPROVED** [review]

**Comment by phyy-nx** [comment]
@ndevenish hey when cctbx/cctbx_project#872 and this PR are merged, the dxtbx and DIALS Azure pipelines will break until the next cctbx conda package release, end of September.  Hence, I'll probably sit on this until about a week before the end of September to give things a chance to settle, meaning the DIALS/dxtbx pipelines will be brokeadoke for that week.  Reasonable?  How does that align with the DIALS release schedule?

Thanks!

**Comment by ndevenish** [comment]
I think we’ll have a DIALS patch release but that’s on a separate history now anyhow.

Does cctbx have a nightly conda-build anywhere we could point at?

**Comment by phyy-nx** [comment]
Yep!  https://github.com/cctbx/cctbx_project#nightly-builds

`conda install -c cctbx-nightly cctbx`

**Comment by ndevenish** [comment]
Okay, this looks like it's now pointing to the nightly CCTBX builds. Once https://github.com/cctbx/cctbx_project/pull/872 is merged, this PR should pass tests (and thus be ready to merge).

**Pull request merged**
