### PR TITLE
Update boost.python → boost_adaptbx.boost.python

### PR DESCRIPTION
**Pull request by ndevenish**
This is to reflect changes added in a series of commits merged in pull cctbx/cctbx_project#516. When the cctbx repository next becomes stable, this will break the dxtbx tests that relied tests with no stderr output, because a warning is printed.

This pull request will fix those tests once those commits are used for testing.

### CODE REVIEW

**Comment by ndevenish** [comment]
Obtained via (thanks @Anthchirp):
```
find . -type f -name "*.py" -print0 | xargs -0 sed -i '' 's/boost\.python/boost_adaptbx.boost.python/g'
find . -type f -name "*.py" -print0 | xargs -0 sed -i '' 's/boost\.optional/boost_adaptbx.boost.optional/g'
find . -type f -name "*.py" -print0 | xargs -0 sed -i '' 's/boost\.std_pair/boost_adaptbx.boost.std_pair/g'
find . -type f -name "*.py" -print0 | xargs -0 sed -i '' 's/boost\.rational/boost_adaptbx.boost.rational/g'
find . -type f -name "*.py" -print0 | xargs -0 sed -i '' 's/boost\.tuple/boost_adaptbx.boost.tuple/g'
find . -type f -name "*.py" -print0 | xargs -0 sed -i '' 's/from boost import/from boost_adaptbx.boost import/g'
```

**Comment by phyy-nx** [comment]
Hi, thanks, I've tested this branch (and that in dials/dials#1379), and all the xfel_regression tests pass.  Thus, when this branch and the dials branch are merged, the XFEL CI builder will be fixed.  That's the only thing failing on cctbx [Azure](https://github.com/cctbx/cctbx_project/runs/1001432328).

The xfel_regression tests use easy_run.raise_if_errors which catches the FutureWarning. That's why when this is merged the cctbx tests will be passing.  So I'd say merge when convenient :) Thanks!

**Comment by ndevenish** [comment]
Ah, if it's literally a circular dependency causing the breakage then it might be worth forcing the ordering. I also wonder if it's worth turning off the mirror check for anything that depends on dials.

**Comment by ndevenish** [comment]
Hopefully this fixes everything 🤞

**Comment by ndevenish** [comment]
I retriggered the failing cctbx Azure tests, but it looks like they are pulling from a cache somewhere; so rather than randomly triggering jobs or trying to work out the order I'll leave it up to you.

**Pull request merged**
