### PR TITLE
Remove useless asserts

### PR DESCRIPTION
**Pull request by graeme-winter**
These should never be triggered but sometimes they were. The actual
definition of get_image_oscillation() here is covered by the checks
above in practice, but sometimes the tests fail with e.g. image ranges
starting from -ve values etc.

This kind of thing:

dxtbx Internal Error: /Users/graeme/git/dials/modules/dxtbx/src/dxtbx/model/scan.h(359): DXTBX_ASSERT(std::min(diff_2pi, diff_abs) < eps * get_num_images()) failure.

I tried chasing down the actual cause without success...

### CODE REVIEW

**Comment by graeme-winter** [comment]
```
    /** Get the total oscillation range of the scan */
    vec2<double> get_oscillation_range() const {
      return vec2<double>(oscillation_[0],
                          oscillation_[0] + num_images_ * oscillation_[1]);
    }
```

The test I am removing should add nothing to tests:

```
      DXTBX_ASSERT(image_range_[1] + 1 == rhs.image_range_[0]);
      DXTBX_ASSERT(std::abs(oscillation_[1] - rhs.oscillation_[1]) < eps);
```

As (following definition above) the oscillation of the `rhs` should start where the current one finishes.

**Comment by graeme-winter** [comment]
Converted to draft while I think some more about what this is trying to achieve, vs. what it actually does. In other news: we probably need some more tests.

**Comment by graeme-winter** [comment]
This is a bad test; sure; but I think it is appearing as we have another weird underlying fault. Keeping this draft while I investigate. 

Yes, I am now spelunking in `dxtbx`

**Comment by graeme-winter** [comment]
OK, so the miniCBF island was OK, and the data appear contiguous when imported, but 

```
65_PdNO2_01_00028.cbf:SCAN1 GONIOMETER_PHI -167.6000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00029.cbf:SCAN1 GONIOMETER_PHI -167.8000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00030.cbf:SCAN1 GONIOMETER_PHI -168.0000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00031.cbf:SCAN1 GONIOMETER_PHI -168.2000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00032.cbf:SCAN1 GONIOMETER_PHI -168.4000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00033.cbf:SCAN1 GONIOMETER_PHI -168.6000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00034.cbf:SCAN1 GONIOMETER_PHI -168.8000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00035.cbf:SCAN1 GONIOMETER_PHI -169.0000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00036.cbf:SCAN1 GONIOMETER_PHI -169.2000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00037.cbf:SCAN1 GONIOMETER_PHI -169.4000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00038.cbf:SCAN1 GONIOMETER_PHI -169.6000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00039.cbf:SCAN1 GONIOMETER_PHI -169.8000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00040.cbf:SCAN1 GONIOMETER_PHI -170.0000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00041.cbf:SCAN1 GONIOMETER_PHI -154.2000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00042.cbf:SCAN1 GONIOMETER_PHI -154.4000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00043.cbf:SCAN1 GONIOMETER_PHI -154.6000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00044.cbf:SCAN1 GONIOMETER_PHI -154.8000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00045.cbf:SCAN1 GONIOMETER_PHI -155.0000 -0.2000 -0.2000 0.0 0.0 0.0
65_PdNO2_01_00046.cbf:SCAN1 GONIOMETER_PHI -155.2000 -0.2000 -0.2000 0.0 0.0 0.0
```

-> that's weird.

**Comment by ndevenish** [comment]
Suspect this should be re-addressed if it becomes an active problem again.

**Pull request closed without merging**
